### ISSUE TITLE
New rule idea: min flow coverage

### ISSUE THREAD

**Issue by cloudkite** [gajus/eslint-plugin-flowtype#100]
I was thinking it would be nice to enforce a minimum coverage percentage. One of the biggest pitfalls of flow IMHO is that when using node modules or other files with no types flow will silently ignore alot of potential errors.

```
coverage-percentage: [2, { "min": 95 }]
```

My biggest concern is the rule would potentially be slow as it would need to spawn the `flow coverage file.js` cli command for each file. While I think flow is pretty quick at retrieving coverage due its incremental nature. Would probably still add up over a project with a lot of files.

We could add a setting for flowBinPath which defaults to just "flow" for users who don't have flow available in their PATH

```
{
  "settings": {
    "flowtype": {
      "flowBinPath": "/usr/custom/flow/bin"
    }
  }
}
```

Yay? Nay? Thoughts?

**Comment by migueloller** [comment]
@cloudkite I think this is a great addition! Also, since Flow gives back information about what specific lines are and aren't covered it is possible to underline the sources of coverage error.

Regarding the overhead, it shouldn't be much after the Flow server starts up.

**Comment by cloudkite** [comment]
@migueloller if you are using nuclide it has a really handy coverage tool does this for you. I find its nice to have this seperate from eslint otherwise you would get alot of noise in your eslint output.  My intention is more to highlight files which need attention due to falling below a coverage threshold then you could use nuclide or cli to investigate further which lines are lacking types.

**Comment by cloudkite** [comment]
@migueloller that said everyones workflow is different so maybe a seperate rule ie `require-complete-coverage` is worth considering

**Comment by cloudkite** [comment]
Closing as came across https://github.com/rpl/flow-coverage-report, which I think is better suited for the task

**Comment by r01010010** [comment]
@cloudkite how `flow-coverage-report` enforces flow use?
