### ISSUE TITLE
[suggestion] add "recommended" configuration

### ISSUE THREAD

**Issue by thealjey** [gajus/eslint-plugin-flowtype#102]
It'd be nice if this package contained "recommended" configuration that a users custom config could extend from, similar to `eslint:recommended` or [plugin:react/recommended](https://www.npmjs.com/package/eslint-plugin-react) or [plugin:lodash/recommended](https://www.npmjs.com/package/eslint-plugin-lodash).
The readme entry for each rule could then say whether it's included in the recommended config or not.

**Comment by gajus** [comment]
https://github.com/gajus/eslint-plugin-flowtype/pull/103
