### ISSUE TITLE
 Error: Failed to load plugin flowtype: Cannot find module './configs/recommended.json'

### ISSUE THREAD

**Issue by borisyankov** [gajus/eslint-plugin-flowtype#110]
Just updated to latest 2.17.0 version and am getting this error:

````
Error: Failed to load plugin flowtype: Cannot find module './configs/recommended.json'
````

**Comment by danharper** [comment]
😨 looking into it now

**Comment by darthtrevino** [comment]
Should this config file exist under the `dist/` folder? If so, I don't see it exist at all in any version of this lib.

**Comment by danharper** [comment]
Yep, that's fixed.

Been trying to ship a release for 15 minutes, didn't quite realise Travis was failing because we depend on our own plugin, which currently has an invalid release out.

So Travis goes to install deps, and our own lint fails because the `eslint-plugin-flowtype` plugin is invalid...

(that wasn't fun lol)

v2.17.1 is building now.

**Comment by danharper** [comment]
`v2.17.1` is now out - thanks everyone for the help! :) .. and sorry for bodging that last release!

**Comment by borisyankov** [comment]
Awesome response time ;)
Thanks.

**Comment by cyberwombat** [comment]
I am still getting this error on 2.20.0. I use standard --fix v8.4.0 and have this in my package.json

````
"standard": {
    "plugins": [
      "flowtype"
    ]
  },
````

**Comment by danharper** [comment]
@cyberwombat What's the exact error?

**Comment by cyberwombat** [comment]
````
Error: Failed to load plugin flowtype: Cannot find module 'eslint-plugin-flowtype'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.load (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/config/plugins.js:129:26)
    at Array.forEach (native)
    at Object.loadAll (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/config/plugins.js:151:21)
    at Config.getConfig (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/config.js:305:17)
    at hashOfConfigFor (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:594:41)
    at executeOnFile (/usr/local/lib/node_modules/standard/node_modules/eslint/lib/cli-engine.js:643:32)
````
I am running this in my repo:
````
standard --fix src/myfile.js
````

Standard and eslint are at latest version.

**Comment by danharper** [comment]
Hm, it seems to be a different issue (can't find the module as opposed to the default config).

I don't use Standard, but if you could create a repo with a minimal reproduction showing this problem, I could look into it?

Could it be a global vs local modules thing? I don't run anything globally, but it looks like you're running `standard` globally. Does `eslint-plugin-flowtype` have to be installed globally too? idk.

**Comment by cyberwombat** [comment]
Standardjs does say to load globally - just read that on their site (or install standard locally). When I do it then it appears that it doesn't use the plugin as my code:
````
function asyncAppViewResolver(viewName: string) {
````

Yields: `Parsing error: Unexpected token :`

You are probably correct that it's a StandardJS config issue. I will continue looking in that direction for a bit then try to reproduce.

**Comment by danharper** [comment]
From that error, it looks like you also need to enable Babel ESLint so that
Babel can parse the files instead.

**Comment by cyberwombat** [comment]
Yup!  Just read [this](https://github.com/eslint/eslint/issues/2157). Looks like the docs on StandardJS about Flow need updating. Thanks!
