### ISSUE TITLE
Add parameter to require-valid-file-annotation to force one style

### ISSUE THREAD

**Issue by chrisnojima** [gajus/eslint-plugin-flowtype#126]
Hi,

Great plugin! 

It'd be awesome if we could specify a specific style for the file annotations. I'd like to force `// @flow` and disallow `/* @flow */`

**Comment by aaron-harvey** [comment]
Addressed in PR #127

**Comment by danharper** [comment]
This is available in v2.20.0 thanks to @aaron-harvey :)
