### ISSUE TITLE
Not all rules respect onlyFilesWithFlowAnnotation

### ISSUE THREAD

**Issue by BernsteinA** [gajus/eslint-plugin-flowtype#128]
In fact, it appears that only requireParameterType, requireValidFileAnnotation, and requireReturnType do.
Of those, requireValidFileAnnotation probably shouldn't anyway.

**Comment by dikmax** [comment]
Looks like `requireValidFileAnnotation` check is wrong.
Right now it shows errors in files with `@noflow` annotation. When this annotation is removed, errors disappears too.

**Comment by danharper** [comment]
Should be sorted now thanks to #155.
