### ISSUE TITLE
Doesn't seem to read .js.flow files with type annotation.

### ISSUE THREAD

**Issue by nirth** [gajus/eslint-plugin-flowtype#14]
I might be doing something wrong. But `eslint-plugin-flowtype` seem to be ignoring non-inline type declarations. [Flow documentation][flow-docs] states that there is three ways to have external type declarations:

 * Inline (plugin seem to be alright with that).
 * Outside of source folder, path declared in `.flowconfig`.
 * And inside source folder, where external type declarations should follow file name conventions of `<filename>.js.flow`.

Are there some more configuraion missing from the README, or features not yet implemented?

[flow-docs]: http://flowtype.org/docs/declarations.html

**Comment by gajus** [comment]
This plugin aims to support only inline declarations. If you'd like to add support for either of the external declaration types, raise a PR.
