### ISSUE TITLE
Space after curly braces?

### ISSUE THREAD

**Issue by arv** [gajus/eslint-plugin-flowtype#146]
Is there a rule that controls whether a space is allowed or not after an object type annotation?

``` js
type T1 = { a: number };
// vs
type T2 = {a: number};
```

**Comment by thealjey** [comment]
@arv `object-curly-spacing` from [eslint-plugin-babel](https://github.com/babel/eslint-plugin-babel)
```json
{
  "babel/object-curly-spacing": [2, "never"]
}
```
For additional info on options refer to [object-curly-spacing - Rules - ESLint](http://eslint.org/docs/rules/object-curly-spacing)

**Comment by gajus** [comment]
@thealjey that doesn't cover types, does it?

**Comment by thealjey** [comment]
@gajus  oh, yep, you're right. It does not, sorry.

**Comment by simlu** [comment]
Is this planned? What would be required? Creating a new rule?

**Comment by gajus** [comment]
Closing as stale. PR is welcome.
