### ISSUE TITLE
Whitelist / blacklist function names for require-return-type et al.

### ISSUE THREAD

**Issue by lime** [gajus/eslint-plugin-flowtype#149]
Feature request: being able to constrain `require-return-type` to only a set number of functions, based on their name.

In this particular case, I would like to enforce explicit return types for the `mapStateToProps` function used in react-redux. Knowing that this function is consistently named throughout my project, whitelisting the name in my `require-return-type` config would do the trick. Something along these lines:

``` json
"flowtype/require-return-type": [
  1,
  "always",
  {
    "includeOnlyMatching": [
      "mapStateToProps"
    ]
  }
],
```

Similarly, I would assume that there exist many use cases for the reverse; enabling the rule for all but a specific list of ignored function names. Something like `excludeMatching`?

Also, this kind of whitelist / blacklist functionality would likely make sense for some other rules as well, such as `require-parameter-type`.

Some related issues are #124 and #57. I don't think either would be solved by this feature, but it could serve as a workaround for situations where all-or-nothing won't work.

**Comment by aaron-harvey** [comment]
Addressed in PR #170
