### ISSUE TITLE
Remove valid-syntax rule or add the meta deprecated flag

### ISSUE THREAD

**Issue by wagerfield** [gajus/eslint-plugin-flowtype#152]
Please could you either remove the `valid-syntax` rule or add `context.meta = { deprecated: true }`

Currently the only place that this rule is documented as being deprecated is in the [`README`](https://github.com/gajus/eslint-plugin-flowtype#valid-syntax)—it would be great to officially recognise this rule as deprecated using the context `meta` object.

**Comment by gajus** [comment]
@wagerfield Please raise a PR.

**Comment by danharper** [comment]
`deprecated: true` added with #156.
