### ISSUE TITLE
npm install, missing several folders

### ISSUE THREAD

**Issue by nicolechung** [gajus/eslint-plugin-flowtype#161]
On `npm install eslint-plugin-flowtype` I appear to be missing several files and folders (src, tests, .scripts, .README)

I have tried uninstalling and installing several times with also using `npm cache clean`.

I also tried doing an `npm install` inside the actual `eslint-plugin-flowtype` folder and then `npm run build`

```babel ./src --out-dir ./dist --copy-files

./src doesn't exist

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/nicolechung/.nvm/versions/node/v6.8.1/bin/node" "/Users/nicolechung/.nvm/versions/node/v6.8.1/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! eslint-plugin-flowtype@2.28.2 build: `babel ./src --out-dir ./dist --copy-files`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the eslint-plugin-flowtype@2.28.2 build script 'babel ./src --out-dir ./dist --copy-files'.```

**Comment by gajus** [comment]
Its intentional. NPM package distributes only the files and folders that are required for use. For anything else, pull the repository code.

If you are looking for the distributable plugin code, see `./dist` folder.

Does this answer your question?

**Comment by nicolechung** [comment]
`./dist` doesn't appear to be one of the folders I got when I did `npm install`.

The reason I am asking is because when I try to run `eslint` I get this message

```
node_modules/.bin/eslint example.js

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-standard-flow". This can happen for a couple different reasons:

1. If ESLint is installed globally, then make sure eslint-plugin-standard-flow is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.

2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm i eslint-plugin-standard-flow@latest --save-dev

If you still can't figure out the problem, please stop by https://gitter.im/eslint/eslint to chat with the team.
```

**Comment by nicolechung** [comment]
I think it does, I might be having an issue with VS Code.
![screen shot 2016-11-29 at 11 52 13 am](https://cloud.githubusercontent.com/assets/771170/20719813/11a30798-b62b-11e6-933e-c7e0efb4fad9.png)

**Comment by danharper** [comment]
It's erroring on `eslint-plugin-flow`, this package is `eslint-plugin-flowtype` - perhaps you have something configured with the wrong package name?

**Comment by nicolechung** [comment]
eslint-plugin-flow is associated with @gajus https://www.npmjs.com/package/eslint-plugin-flow ? I'm wondering if npm/node does something with that association that VSCode does not (since it works via command line right now without a problem)

**Comment by danharper** [comment]
Could you post your `.eslintrc`? Do you have `eslint-plugin-flow` in your `node_modules`?

**Comment by nicolechung** [comment]
I can but I suspect it might be a `visual studio code` issue (and I posted on their repo already). Like you probably won't find anything weird if you run it without Visual Studio Code.

Should I just close this issue?

**Comment by danharper** [comment]
Yeah, does sound like something odd with VSCode. I'd just find where you have `eslint-plugin-flow` and remove that, as it shouldn't be installed.
