### ISSUE TITLE
$Enum feature is not supported

### ISSUE THREAD

**Issue by nbotalov** [gajus/eslint-plugin-flowtype#171]
I'm using $Enum feature - http://sitr.us/2015/05/31/advanced-features-in-flow.html#enumt
```
const Statuses = {
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    DONE: 'DONE'
};
type UploadStatus = $Enum<typeof Statuses>;
```

And got eslint error:

```
_21:21  error    '$Enum' is not defined              no-undef_
```

Another declarations like `$Diff`, `$Shape` etc are not working as well.

My configuration:

* webpack
* babel ("transform-flow-strip-types", "syntax-flow" plugins)
* eslint ("react", "flowtype" plugins)

**Comment by danharper** [comment]
Have you configured the [`define-flow-type`](https://github.com/gajus/eslint-plugin-flowtype#define-flow-type) rule? That should suppress all Flow `no-undef` errors.

Btw, unrelated to this error, I think `$Enum` is deprecated in favour of `$Keys` ([see these comments](https://github.com/facebook/flow/blob/eeccd8bc64e435e34084ab43b36a42faabb54483/src/typing/type_annotation.ml#L261-L263)).
