### ISSUE TITLE
Disallow flowtypes without @flow annotation

### ISSUE THREAD

**Issue by aldendaniels** [gajus/eslint-plugin-flowtype#176]
We're considering migrating a large codebase to use flow over time. As we migrate files, we'll add the `@flow` comment to files that we annotate. Today, it's easy to forget to add the `@flow` comment. When this happens, the type annotations appear valid, even though they aren't enforced. It would be nice to disallow flow annotations if the `@flow` comment is not defined.

**Comment by kevinbarabash** [comment]
I just forgot it on a couple of files I was converting.  Thankfully, my code reviewer caught it.

**Comment by aaron-harvey** [comment]
I've added a new rule to cover this (PR #180)

**Comment by micaste** [comment]
Closed by #222 and #223

**Comment by gajus** [comment]
Thank you
