### ISSUE TITLE
The space-after-colon rule does not work for variable delcarations

### ISSUE THREAD

**Issue by aldendaniels** [gajus/eslint-plugin-flowtype#178]
With:
```javascript
'flowtype/space-after-type-colon': [2, 'always'],
```

This is allowed:
```javascript
const x:number = 7;
```

**Comment by aaron-harvey** [comment]
Addressed in PR#179

**Comment by aldendaniels** [comment]
@aaron-harvey wow, thanks for quick fix! Your tests cover `const` and `let` but not `var`. Will this work for `var` declarations as well? Not that there's a likely reason to be using `var`...

**Comment by aaron-harvey** [comment]
@aldendaniels the `VariableDeclaration` hook includes var - I've added another test case to clarify this as well.

**Comment by gajus** [comment]
Closing as stale.
