### ISSUE TITLE
Does this require flow-bin?

### ISSUE THREAD

**Issue by ryancole** [gajus/eslint-plugin-flowtype#185]
This question is likely going to sound dumb, but does this plugin require flow-bin? I currently do not have flow-bin installed and it does not appear that I'm seeing any flowtype-related eslint errors, despite purposely making some to test. I'm not seeing any errors from eslint itself though due to a missing flow-bin. Also, flow-bin isn't in peer dependencies so I figure it's not needed?

Thanks.

**Comment by amilajack** [comment]
Dont worry about how your question sounds. All questions are welcome!

It is not required. [Here's a short guide](https://github.com/amilajack/eslint-plugin-flowtype-errors/wiki/Getting-Started#from-scratch-setup) on installing another flowtype plugin. Just substitute `eslint-plugin-flowtype-errors` for `eslint-plugin-flowtype`

**Comment by danharper** [comment]
Yep, this plugin doesn't run Flow, or enforce your types - you need Flow for that (or, use `eslint-plugin-flowtype-errors` which runs Flow within ESLint).

This plugin just enforces stylistic changes for type annotations.

**Comment by ryancole** [comment]
Gotcha! Thanks for the explanations. 👍
