### ISSUE TITLE
generic arrow functions trigger `no-undef`

### ISSUE THREAD

**Issue by davidaurelio** [gajus/eslint-plugin-flowtype#186]
Generic functions trigger `no-undef`, even though I have `flowtype/define-flow-type` activated (set to `"warn"`).

The minimal repro is: 

```js
type F = <T>(T) => [T];
```

with the following errors:
```
  1:18  error  'T' is not defined  no-undef
  1:21  error  'T' is not defined  no-undef
  1:28  error  'T' is not defined  no-undef

✖ 3 problems (3 errors, 0 warnings)
```

I am aware that the example can be expressed as `export type F<T> = (T) => [T];`, but that isn’t always possible, e.g. if the type is an intersection/union of generic function types.

**Comment by danharper** [comment]
I'm not able to replicate this, here's a sample repo: https://github.com/danharper/temp-repro-flowtype-186/tree/master

With `flowtype/define-flow-type` enabled, `no-def` doesn't error.

**Comment by gajus** [comment]
Closing as stale.
