### ISSUE TITLE
Type alias for arrow function throws error for require-return-type / require-parameter-type

### ISSUE THREAD

**Issue by thejohnbackes** [gajus/eslint-plugin-flowtype#191]
About two weeks ago I implemented require-return-type and require-parameter type. After this I noticed eslint-flowtype is throwing an error if I create a type alias for a method.

![image](https://cloud.githubusercontent.com/assets/13596692/22226815/da1969fc-e17c-11e6-82e2-bc748b43fe9c.png)

It seems like the intended behavior would be to recognize "id" as (?string | ?number) and the return value as string. Am I interpreting this incorrectly?

**Comment by danharper** [comment]
This will actually be addressed with #182 :) I'll try and release it tomorrow.

**Comment by leemhenson** [comment]
Is there any extra work needed to get this one out? Happy to take look.

**Comment by gajus** [comment]
Addressed in https://github.com/gajus/eslint-plugin-flowtype/pull/182/.
