### ISSUE TITLE
require-variable-type: Disable for arrow functions

### ISSUE THREAD

**Issue by joncursi** [gajus/eslint-plugin-flowtype#198]
Would be great if require-variable-type allowed you to disable the rule for functions created with ES6 const notation. These functions are already inherently typechecked by their arguments and return value being typechecked (linting available in other rules), so typechecking the variable on top of that is super duplicative:

```js
import type { DurationFlowType } from '../../types/duration';

const getDuration: (seconds: number) => DurationFlowType = (seconds: number): DurationFlowType => {
  ...
}
```

This is less code and is just as expressive:

```js
import type { DurationFlowType } from '../../types/duration';

const getDuration = (seconds: number): DurationFlowType => {
  ...
}
```

**Comment by uwap** [comment]
yes, it might enhance readability on const declarations and add clarification to require type definitions. In the case of arrow function it does not make a lot of sense though.

**Comment by gajus** [comment]
Closing as stale.
