### ISSUE TITLE
TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by volkanunsal** [gajus/eslint-plugin-flowtype#199]
I have been getting this error today from this package. Does anyone know why this might be happening?

```
TypeError: Cannot read property 'range' of null
    at TokenStore.getTokenAfter (/node_modules/eslint/lib/token-store/index.js:338:17)
    at getSpacesAfterColon (/node_modules/eslint-plugin-flowtype/dist/rules/spaceAfterTypeColon.js:39:32)
```
This is the flowtype code in question:

```js
var colon = sourceCode.getFirstToken(node, node.optional ? 2 : 1);

return {
  colon: colon,
  spaceAfter: sourceCode.getTokenAfter(colon).start - colon.end
};
```

**Comment by volkanunsal** [comment]
The issue is coming from these two rules:

```
'flowtype/space-after-type-colon'
'flowtype/space-before-type-colon'
```

**Comment by wyze** [comment]
This might be fixed by #197, but I didn't confirm that.

**Comment by gajus** [comment]
has this been fixed?

**Comment by mvolkmann** [comment]
This is hitting me hard today. I can't get any linting to work because of this.
spaceAfterTypeColon.js line 39 calls getTokenAfter which is defined in eslint/lib/token-store/index.js line 338. That's where you'll see `node.range` and node is undefined.

**Comment by gajus** [comment]
Closing as stale.
