### ISSUE TITLE
`space-before-type-colon` doesn't seems to work

### ISSUE THREAD

**Issue by StyMaar** [gajus/eslint-plugin-flowtype#20]
`flowtype/space-after-type-colon` works well in my case, but it's before counterpart does not. 

I'll post a simple repro asap.

**Comment by gajus** [comment]
@StyMaar are you providing more debug information?

**Comment by tornewuff** [comment]
Seems not to work for me either. Trivial repro:

```javascript
/* eslint flowtype/space-before-type-colon: [2, "never"] */
function foo (x : string) : string { return x }
```

run with `eslint --parser babel-eslint --plugin flowtype` reports no errors.
