### ISSUE TITLE
continuous-integration bot released v2.30.0 twice

### ISSUE THREAD

**Issue by hawkrives** [gajus/eslint-plugin-flowtype#202]
Both travis builds [439](https://travis-ci.org/gajus/eslint-plugin-flowtype/builds/204893006) and [419](https://travis-ci.org/gajus/eslint-plugin-flowtype/builds/192132510) were determined to be v2.30.0, for some reason.

Build 439 then failed to make a new git tag, since it already existed, and so the released v2.30.0 (from min-January) is missing the eslint@3.16 fix from #197.

I'm not familiar enough with your infrastructure to diagnose anything further, I'm afraid.

Have a great day!

**Comment by gajus** [comment]
Its been fixed.
