### ISSUE TITLE
Reducing overhead of lodash dependency

### ISSUE THREAD

**Issue by segphault** [gajus/eslint-plugin-flowtype#205]
Taking a dependency on lodash in its entirety adds about 5MB of overhead on disk. It looks like you are only using 12 functions, many of them only once or twice. Some of them, like forEach, can probably be replaced with built-ins. You could reduce the overhead of your package by depending on packages for the specific individual functions that you really need and rewriting the code to avoid using lodash in cases where you don't.

```
$ grep -ohR "_\.[a-zA-Z]\+" * | sort | uniq
_.find _.forEach _.forIn _.get _.has _.includes _.isEqual _.isPlainObject _.last _.mapValues _.partial _.some
```

**Comment by gajus** [comment]
Get a bigger hard disk.
