### ISSUE TITLE
Incorporate eslint-plugin-flow-check

### ISSUE THREAD

**Issue by marionebl** [gajus/eslint-plugin-flowtype#206]
I recently published `eslint-plugin-flow-check` ([link](https://github.com/marionebl/eslint-plugin-flow-check)). 

I am rather unhappy with crowding the eslint + flowtype naming space further but had to move quickly for a private project. 

I wonder if you'd be interested in incorporating the plugins functionality in yours and share the maintenance burden.

**Comment by gajus** [comment]
Are you familiar with https://github.com/amilajack/eslint-plugin-flowtype-errors ?

It appears that your plugin does the same.

**Comment by marionebl** [comment]
@gajus I opened an issue to involve @amilajack. Would you be interested in incorporating `flow check` functionality in your plugin by joining efforts?

**Comment by gajus** [comment]
@marionebl https://github.com/gajus/eslint-plugin-flowtype/pull/175

**Comment by marionebl** [comment]
Thanks

**Comment by amilajack** [comment]
>  Would you be interested in incorporating flow check functionality in your plugin by joining efforts?

I'm not sure what you mean by this. Also would be great if you could create an issue in the flowtype-errors repo so we can move the discussion there. Thanks!
