### ISSUE TITLE
babel-eslint changes

### ISSUE THREAD

**Issue by zertosh** [gajus/eslint-plugin-flowtype#209]
FYI: https://github.com/babel/babel-eslint/pull/449, fixed some issues with scoping of type params that are now causing `no-unused-vars` and `no-undef`'s test to fail. I'm fixing a few more issues wrt scoping that'll cause a few more of those tests to fail. When that's done, I'm come by here and update those rules and their tests. These changes don't affect the functioning of `no-unused-vars` and `no-undef`, but it does make some of their code unnecessary.

**Comment by gajus** [comment]
Closing as stale.
