### ISSUE TITLE
Default parameters with notations

### ISSUE THREAD

**Issue by montogeek** [gajus/eslint-plugin-flowtype#21]
Hi!

I am getting this error: `error  'string' is not defined  no-undef` on this code:

```js
login: (data : Object = { username: string, password: string }): Promise => {
   // code
 },
```

It is supported?

This is a screenshot from Atom:
![screen shot 2016-05-09 at 13 20 09](https://cloud.githubusercontent.com/assets/1002461/15123301/d1dd5f2e-15e8-11e6-9699-7d67fd2ae0f9.png)

Thanks :)

I am using the latest version of Flow, ESLint, Babel ESLint and this plugin :)

**Comment by gajus** [comment]
This ought to work fine. Can you create a repository to reproduce it?

**Comment by montogeek** [comment]
Hi @gajus I ended removing the `Object` notation, like this:
```
login: (data :  { username: string, password: string }): Promise => {
   // code
 },
```

Now it works, I did it after reading Flow docs :)
