### ISSUE TITLE
Make flowtype/sort-keys fixable

### ISSUE THREAD

**Issue by jpolo** [gajus/eslint-plugin-flowtype#212]
Hi,

It would be nice to make the rule named `flowtype/sort-keys` auto-fixable. Differently from the object key sorting, it should not be as difficult because there is no side effects related.

Thanks

**Comment by deecewan** [comment]
just started working on this. @gajus I can't actually see where the rules are specified as `fixable`. For example, in the `booleanStyle.js` rule, there is no mention of `fixable`, however the README mentions that it is in fact fixable.

Could you point me in the right direction?

**Comment by gajus** [comment]
The `fix` method, e.g. https://github.com/gajus/eslint-plugin-flowtype/blob/6eceb89551700701bad8a9d9ab5cab084f3a44fe/src/rules/booleanStyle.js#L17-L19

**Comment by gajus** [comment]
This might come handy too https://github.com/eslint/eslint/pull/7715

**Comment by deecewan** [comment]
@gajus i figured I can just add the `fix` method, without updating the metadata of the rule - i imagine this is due to the older version of ESLint in use?

**Comment by gajus** [comment]
> @gajus i figured I can just add the fix method, without updating the metadata of the rule - i imagine this is due to the older version of ESLint in use?

I am not familiar with the API changes in the recent version of the ESLint.

**Comment by deecewan** [comment]
From [here](https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes), they mention that 

> Unless the rule exports the `meta.fixable` property, ESLint does not apply fixes even if the rule implements fix functions.

**Comment by gajus** [comment]
Might be a good cause for another PR. :-)
