### ISSUE TITLE
define-flow-type does not suppress warnings for core private types

### ISSUE THREAD

**Issue by gajus** [gajus/eslint-plugin-flowtype#214]
`$ReadOnlyArray` will trigger `no-undef` rule.

**Comment by gajus** [comment]
@danharper Is it intentional or an oversight?

**Comment by gajus** [comment]
To be more specific,

```js
(a): Promise<$ReadOnlyArray<number>> => {}

```

Triggers the error.

**Comment by gajus** [comment]
Sorry, issue in my local setup.

**Comment by sobolevn** [comment]
@gajus how did you fix it?
