### ISSUE TITLE
Warn/Error if there's no // @flow

### ISSUE THREAD

**Issue by svipben** [gajus/eslint-plugin-flowtype#215]
Hello,

there is config for `// @flow` comment check? I mean if I open `.js`/`.jsx` file without `// @flow` I get warn/error to add it, if there is no config, I think it will be good idea to add it, because sometimes I forget to insert `// @flow`.

Thanks

**Comment by svipben** [comment]
Sorry, I found it `require-valid-file-annotation`, I'm so happy, very very good plugin!

**Comment by kevinbarabash** [comment]
`require-valid-file-annotation` no longer warns when there's no `// @flow`.  The [docs](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-valid-file-annotation) also show that a file without the annotation is not considered a problem.
