### ISSUE TITLE
require-return-type exclude or include not working

### ISSUE THREAD

**Issue by svipas** [gajus/eslint-plugin-flowtype#217]
`"flowtype/require-return-type": ["error", "always", { "excludeMatching": ["render"] }],`

`render()` which is inside `App` class get error which says you missed return type annotation, also `includeOnlyMatching` doesn't working too.

P.S. It just don't works for any word.

**Comment by AtticusFetch** [comment]
Same for me. Any updates ?

**Comment by gajus** [comment]
@AtticusFetch PR is welcome.

**Comment by grit96** [comment]
I have a related issue. Using `"excludeMatching": ["render"]`, the render instance method is excluded but when written as a function it is not excluded:

```js
class ContactsView extends Component<PropsType, StateType> {
  render() { // This is excluded
  }

  render = () => { // Written like this it is not excluded
  }
}
```

I want to write some class methods like this to avoid having to bind them in the constructor.

**Comment by gajus** [comment]
Already fixed.
