### ISSUE TITLE
suppress_comment in .flowconfig is not working.

### ISSUE THREAD

**Issue by 0rangeT1ger** [gajus/eslint-plugin-flowtype#218]
my `Button.js`
```
  // $FlowFixMe  string is incompatible with ReactClass
  component: string | ReactClass<*>,
```
my flowconfig
```
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe
```

It worked fine with flow alone.
When it comes to lint, the suppress comment didn't work.

**Comment by gajus** [comment]
`eslint-plugin-flowtype` has no knowledge of `.flowconfig`.

**Comment by 0rangeT1ger** [comment]
Why suppress it twice, one in `suppress_comment` and one in `eslint-disable`?
It doesn't make sense.
