### ISSUE TITLE
When using Async/Await annotating as Promise<void> does not work with annotateUndefined.

### ISSUE THREAD

**Issue by AriaFallah** [gajus/eslint-plugin-flowtype#22]
With the following:

```js
async function doThing(): Promise<void> {}
```

a promise is implicitly returned and flow requires that you annotate it as a promise.

If you have `{ "annotateUndefined": true }`, this plugin does not accept throws an error since `Promise<void>` is not `undefined`.

**Comment by gajus** [comment]
Fixed thanks to @danharper! 👍

**Comment by jedwards1211** [comment]
I think this is broken again in 3.6.1?  I upgraded today and got a bunch of errors
