### ISSUE TITLE
Definition for rule 'flowtype/boolean-style' was not found (flowtype/boolean-style)

### ISSUE THREAD

**Issue by gHashTag** [gajus/eslint-plugin-flowtype#226]
How to fix it?
`import React, { Component } from 'react'`

**Comment by gajus** [comment]
What version of `eslint-plugin-flowtype` have you got installed?

**Comment by gHashTag** [comment]
@gajus 
I have a file [.eslintrc](https://github.com/gHashTag/AwesomeProjectForVim/blob/master/.eslintrc)
My [.vimrc](https://gist.github.com/gHashTag/67248af179a19161f6d7abb354f49ad0)
 Do I need to merge the settings eslint and flow so? 

```
{
    "extends": "airbnb",
    "parser": "babel-eslint",
    "plugins": [
        "react",
        "react-native",
	"flowtype"
    ],
    "parserOptions": {
        "ecmaVersion": 6,
        "sourceType": "module",
        "ecmaFeatures": {
            "jsx": true,
            "modules": true
        }
    },
    "env": {
        "browser": true,
        "node": true,
        "jquery": true
    },
    "settings": {
      "flowtype": {
            "onlyFilesWithFlowAnnotation": false
      },
      "react": {
            "pragma": "React",
            "version": "15.1.0"
      },
        "ecmascript": 6,
        "jsx": true
    },
    "rules": {
	"flowtype/boolean-style": [
      2,
      "boolean"
    ],
    "flowtype/define-flow-type": 1,
    "flowtype/delimiter-dangle": [
      2,
      "never"
    ],
    "flowtype/generic-spacing": [
      2,
      "never"
    ],
    "flowtype/no-primitive-constructor-types": 2,
    "flowtype/no-types-missing-file-annotation": 2,
    "flowtype/no-weak-types": 2,
    "flowtype/object-type-delimiter": [
      2,
      "comma"
    ],
    "flowtype/require-parameter-type": 2,
    "flowtype/require-return-type": [
      2,
      "always",
      {
        "annotateUndefined": "never"
      }
    ],
    "flowtype/require-valid-file-annotation": 2,
    "flowtype/semi": [
      2,
      "always"
    ],
    "flowtype/space-after-type-colon": [
      2,
      "always"
    ],
    "flowtype/space-before-generic-bracket": [
      2,
      "never"
    ],
    "flowtype/space-before-type-colon": [
      2,
      "never"
    ],
    "flowtype/type-id-match": [
      2,
      "^([A-Z][a-z0-9]+)+Type$"
    ],
    "flowtype/union-intersection-spacing": [
      2,
      "always"
    ],
    "flowtype/use-flow-type": 1,
    "flowtype/valid-syntax": 1,
        "react-native/no-unused-styles": 2,
        "react-native/split-platform-components": 2,
        "react-native/no-inline-styles": 2,
        "react-native/no-color-literals": 0,
        "react/jsx-filename-extension": 0,
        "react/prefer-stateless-function": 0,
        "strict": 0,
        "quotes": 0,
        "no-unused-vars": 1,
        "camelcase": 1,
        "no-underscore-dangle": 1,
        "comma-dangle": [1, "never"],
        "indent": ["error", 4],
        "react/jsx-indent": 0,
        "react/jsx-equals-spacing": [2, "never"],
        "no-use-before-define": ["error", {
            "variables": false
        }],
        "semi": ["error", "never"],
        "arrow-body-style": 0,
        "no-console": 0,
        "max-len": 1,
        "no-param-reassign": 1,
        "no-multi-spaces": [
            2,
        {
          "exceptions": {
                    "VariableDeclarator": true,
                    "ImportDeclaration": true,
                    "JSXAttribute": true,
                    "AssignmentExpression": true
          }
            
        }
        
        ]
    }
}
```

**Comment by gajus** [comment]
You've not answered the question.

**Comment by gHashTag** [comment]
@gajus 
eslint-plugin-flowtype": "^2.32.1

**Comment by gajus** [comment]
I cannot think of a reason. Whats the output of:

```bash
$ tree ./node_modules/eslint-plugin-flowtype

```

?

**Comment by gHashTag** [comment]
$ tree ./node_modules/eslint-plugin-flowtype
./node_modules/eslint-plugin-flowtype
├── CONTRIBUTING.md
├── LICENSE
├── README.md
├── bin
│   └── readmeAssertions.js
├── dist
│   ├── configs
│   │   └── recommended.json
│   ├── index.js
│   ├── rules
│   │   ├── booleanStyle.js
│   │   ├── defineFlowType.js
│   │   ├── delimiterDangle.js
│   │   ├── genericSpacing.js
│   │   ├── noDupeKeys.js
│   │   ├── noPrimitiveConstructorTypes.js
│   │   ├── noTypesMissingFileAnnotation.js
│   │   ├── noWeakTypes.js
│   │   ├── objectTypeDelimiter.js
│   │   ├── requireParameterType.js
│   │   ├── requireReturnType.js
│   │   ├── requireValidFileAnnotation.js
│   │   ├── requireVariableType.js
│   │   ├── semi.js
│   │   ├── sortKeys.js
│   │   ├── spaceAfterTypeColon.js
│   │   ├── spaceBeforeGenericBracket.js
│   │   ├── spaceBeforeTypeColon.js
│   │   ├── typeColonSpacing
│   │   │   ├── evaluateFunctions.js
│   │   │   ├── evaluateObjectTypeIndexer.js
│   │   │   ├── evaluateObjectTypeProperty.js
│   │   │   ├── evaluateReturnType.js
│   │   │   ├── evaluateTypeCastExpression.js
│   │   │   ├── evaluateTypical.js
│   │   │   ├── index.js
│   │   │   └── reporter.js
│   │   ├── typeIdMatch.js
│   │   ├── unionIntersectionSpacing.js
│   │   ├── useFlowType.js
│   │   └── validSyntax.js
│   └── utilities
│       ├── checkFlowFileAnnotation.js
│       ├── fuzzyStringMatch.js
│       ├── getParameterName.js
│       ├── getTokenAfterParens.js
│       ├── getTokenBeforeParens.js
│       ├── index.js
│       ├── isFlowFile.js
│       ├── isFlowFileAnnotation.js
│       ├── iterateFunctionNodes.js
│       ├── quoteName.js
│       └── spacingFixers.js
└── package.json

6 directories, 48 files

**Comment by gajus** [comment]
No clue. The file is clearly there.

**Comment by gHashTag** [comment]
I restarted the project here is what error:
> Missing return type annotation. (flowtype/require-return-type)

This is boilerplate React Native (react-native-cli)
![2017-04-28 11 42 42](https://cloud.githubusercontent.com/assets/6774813/25521351/dca5b4c0-2c07-11e7-9c63-026a4acd6fab.png)

**Comment by gajus** [comment]
> I restarted the project here is what error: [..]

Read the documentation.

**Comment by lo-corp** [comment]
To fix this issue just run `npm install eslint-plugin-flowtype` in the root directory of your project.

What's causing this issue is, eslint is looking for the `eslint-flowtype-plugin`'s linting rules locally instead of the global installation. 

Gajus can find this issue, all other plugins work fine. Only the flowtype-plugin is being digged locally by `eslint`.
