### ISSUE TITLE
"excludeArrowFunctions: expressionsOnly" breaks require-return-type

### ISSUE THREAD

**Issue by rbong** [gajus/eslint-plugin-flowtype#232]
If you set `[2, { excludeArrowFunctions: 'expressionsOnly' }]`, the rule will never give an error.

**Comment by Whoaa512** [comment]
@rbong The expected options format is `[ENABLE_VALUE, 'always', OPTIONS]`, so I believe if you add `'always'` in between your object and the 2 it should work.
