### ISSUE TITLE
Doesn't work with .vue files

### ISSUE THREAD

**Issue by igidas** [gajus/eslint-plugin-flowtype#235]
Hey, thanks for a plugin!

But I can't get it working with` .vue` files. They are compiled with `eslint-plugin-html` plugin.
Looks like your code with check if `isFlowFile` looks only the first comment reported by Eslint.
But the comment object of Eslint then compilling `.vue` always starts with HTML comment:`
```
comments [ { type: 'Block',
    value: ' HTML ',
    start: 0,
    end: 10,
    loc: SourceLocation { start: [Object], end: [Object] },
    range: [ 0, 10 ] },
  { type: 'Line',
    value: ' @flow',
    start: 10,
    end: 24,
    loc: SourceLocation { start: [Object], end: [Object] },
    range: [ 10, 24 ] },
...
````

Example of `.vue`:
```
<script>
    // @flow
   ...
</script>
```

**Comment by gajus** [comment]
Does Flow in general work with `.vue` files?

**Comment by igidas** [comment]
Currently only via Eslint: https://alligator.io/vuejs/components-flow/
It just uses **eslint-plugin-flowtype-errors** plugin.

**Comment by opeadeyomoye** [comment]
Hi @gajus, any idea whether this enhancement is on the roadmap?

**Comment by gajus** [comment]
I don't plan to add support for Vue files, but would accept a PR. In the meantime, closing as stale.
