### ISSUE TITLE
Add a rule that requires to use $ReadOnlyArray instead of Array

### ISSUE THREAD

**Issue by gajus** [gajus/eslint-plugin-flowtype#236]
Rule must warn when `Array` is used instead of [`$ReadOnlyArray`](https://github.com/facebook/flow/blob/v0.46.0/lib/core.js#L185).

**Comment by pnevyk** [comment]
@gajus I am working on this. And I have basically three questions:

* Should this rule apply also on `string[]` notation? I would guess so. It should be probably configurable.
* Does this rule need any specific configuration (apart from one mentioned above)? For example to specify exceptions for this rule somehow, or any other.
* Do you have a nice text about reason for this use? I think it should be noted in the docs. I found [this general article about immutability](https://medium.com/@yej.arin.choi/this-is-a-post-that-summarizes-my-dive-into-immutability-in-programming-what-it-is-why-its-34cbba44f889) and some Flow issues where `$ReadOnlyArray` solves problems with `Array` ([1](https://github.com/facebook/flow/issues/3425), [2](https://github.com/facebook/flow/issues/4251)).

**Comment by gajus** [comment]
> Should this rule apply also on string[] notation?

Yes. Regardless of whether the array contains primitive data or not, it is mutable. There is no short-hand syntax for non-mutable array.

> Does this rule need any specific configuration (apart from one mentioned above)? For example to specify exceptions for this rule somehow, or any other.

I cannot think of any exceptions.

It should always require to use `$ReadOnlyArray`. When user intends to use `Array`, he should use `// eslint-disable-next-line require-read-only-array`.

> Do you have a nice text about reason for this use? I think it should be noted in the docs. I found this general article about immutability and some Flow issues where $ReadOnlyArray solves problems with Array (1, 2).

All generic pro-immutable data arguments apply, e.g.

* immutable objects are simpler to construct, test, and use
* they help to avoid temporal coupling
* their usage is side-effect free (no defensive copies)
* identity mutability problem is avoided
* they always have failure atomicity
* they are much easier to cache

– https://softwareengineering.stackexchange.com/questions/151733/if-immutable-objects-are-good-why-do-people-keep-creating-mutable-objects

**Comment by pnevyk** [comment]
@gajus This is already [merged](https://github.com/gajus/eslint-plugin-flowtype/pull/279). You can close this issue.
