### ISSUE TITLE
Utility types are considered undefined

### ISSUE THREAD

**Issue by irnc** [gajus/eslint-plugin-flowtype#239]
ESLint warns that `$Supertype is not defined.` when using type annotation `$Supertype<SomeType>` in a create-react-app project which uses `eslint-plugin-flowtype@2.34.0`.

`$Supertype` should be considered as always defined, because it is [defined by Flow](https://flow.org/en/docs/types/utilities/#toc-supertype) itself.

Workaround to suppress a warning might be adding `/* global $Supertype */`, but it looks strange from a semantic point of view.

**Comment by danharper** [comment]
You need to enable the `define-flow-type` rule which marks Flow identifies as defined.
