### ISSUE TITLE
`no-unused-vars` shouldn't complain for function parameters

### ISSUE THREAD

**Issue by indigoviolet** [gajus/eslint-plugin-flowtype#24]
For callbacks etc, it seems common to have function parameters that are declared (for documentation/to conform to the signature) but not used.

**Comment by danharper** [comment]
Hi, it seems this issue's actually for the ESLint `no-unused-vars` rule, and shouldn't be effected by this plugin.

These options may help: http://eslint.org/docs/rules/no-unused-vars#options (e.g. `{args: 'none'}` or `{args: 'after-used'}`.
