### ISSUE TITLE
Files without @flow comment are throwing errors

### ISSUE THREAD

**Issue by jasonify** [gajus/eslint-plugin-flowtype#243]
I am seeing eslint throw this error (a lot):

` 23:17  error  Type annotations require valid Flow declaration  flowtype/no-types-missing-file-annotation`

For files that don't have /* @flow */ anywhere in the file.

eslint: 

In package.json:
```
"babel-eslint": "^7.1.1",
"eslint": "^3.16.1",

"eslint-plugin-flowtype": "^2.30.0",
```

Any ideas would be helpful.

.flowconfig:

```
[include]
src/client

```
So not sure if that's causing problems since I am effectively running:

`eslint src/client`

Thanks

**Comment by luftywiranda13** [comment]
have you tried to remove `src/client` from the `include` section?

**Comment by jasonify** [comment]
I have. It still throws the same number of errors.

**Comment by luftywiranda13** [comment]
btw does the error come from `eslint` or `flow` itself?

**Comment by luftywiranda13** [comment]
hmmm i think you missed the purpose of the rule itself. try to read https://github.com/gajus/eslint-plugin-flowtype#no-types-missing-file-annotation

**Comment by jasonify** [comment]
Not sure that I follow, I am not using that rule anywhere in my project?


Here is the configuration file, I just added the `settings` section to the .eslintrc file after reading the docs above:


```
{
  "extends": [
    "standard",
    "plugin:flowtype/recommended",
    "plugin:no-unused-vars-rest/recommended"
  ],
  "parser": "babel-eslint",
  "plugins": ["react", "flowtype"],
  "env": {
    "node": true,
    "browser": true,
    "jest": true
  },
 "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  },
  "rules": {
    "react/jsx-uses-react": 1,
    "react/jsx-uses-vars": 1,
    "comma-dangle": 0,
    "camelcase": 0,
    "no-unused-vars-rest/no-unused-vars": [2, {
        "ignoreDestructuredVarsWithRest": true,
        "args": "after-used",
        "argsIgnorePattern": "^_"
    }]
  }
}

```


Adding this `settings` sections actually causes more errors.



`flowtype/no-types-missing-file-annotation` is not in the project as far as I can tell. The documentation doesn't really make it clear why it's defined as a 2?

**Comment by gajus** [comment]
> Not sure that I follow, I am not using that rule anywhere in my project?

[`flowtype/no-types-missing-file-annotation` is part of the recommended configuration](https://github.com/gajus/eslint-plugin-flowtype/blob/42328cd8b081eb60da4a9b65b920dda155d35d8e/src/configs/recommended.json#L14), which you show to be using in your example configuration.

**Comment by billyjanitsch** [comment]
@gajus wasn't adding it to the recommended configuration a breaking change? (As is the case for adding any new rule to an existing config.)

**Comment by gajus** [comment]
> @gajus wasn't adding it to the recommended configuration a breaking change? (As is the case for adding any new rule to an existing config.)

Open to debate. I see the recommended rules and the main plugin as separate projects.

In general, managing versioning of ESLint rules is a tricky subject. In effect, every rule change is a breaking change and thus would require a major version version bump.

**Comment by gajus** [comment]
Closing as stale.
