### ISSUE TITLE
flow linting errors showing, even with no mention @flow in file

### ISSUE THREAD

**Issue by TomYeoman** [gajus/eslint-plugin-flowtype#245]
Hi all,

I've got a strange situation where my files seem to be getting partially "flow linted" even before i've got "// @flow " at the top of the file

Here is the setup

**Eslint alone - 20 errors**

Config:

```
{
  "extends": "airbnb",
  "globals": {"window": true, "document": true, "$": true, "location": true },
  "rules": {
      "indent": ["error", 4, { "SwitchCase": 1 }],
      "linebreak-style": ["off"],
      "no-plusplus": ["off"],
      "no-undef": ["off"],
      "no-use-before-define": ["off"],
      "no-underscore-dangle": ["off"],
      "max-len": ["error", { "ignoreComments": true, "code": 150 }]
  },
    "parserOptions": {
        "sourceType": "module",
    }
}

```

**Eslint + Flow eslint rules - 80 errors**

Config: 

```
{
    "extends": ["airbnb", "plugin:flowtype/recommended"],
    "globals": {
        "window": true,
        "document": true,
        "$": true,
        "location": true
    },
    "rules": {
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
        "linebreak-style": [
            "off"
        ],
        "no-plusplus": [
            "off"
        ],
        "no-undef": ["off"],
        "no-use-before-define": ["off"],
        "no-underscore-dangle": ["off"],
        "max-len": ["error", { "ignoreComments": true, "code": 150 }],
        "flowtype/boolean-style": [
            2,
            "boolean"
        ],
        "flowtype/define-flow-type": 1,
        "flowtype/delimiter-dangle": [
            2,
            "never"
        ],
        "flowtype/generic-spacing": [
            2,
            "never"
        ],
        "flowtype/no-primitive-constructor-types": 2,
        "flowtype/no-types-missing-file-annotation": 2,
        "flowtype/no-weak-types": 2,
        "flowtype/object-type-delimiter": [
            2,
            "comma"
        ],
        "flowtype/require-parameter-type": 2,
        "flowtype/require-return-type": [
            2,
            "always",
            {
                "annotateUndefined": "never"
            }
        ],
        "flowtype/require-valid-file-annotation": 2,
        "flowtype/semi": [
            2,
            "always"
        ],
        "flowtype/space-after-type-colon": [
            2,
            "always"
        ],
        "flowtype/space-before-generic-bracket": [
            2,
            "never"
        ],
        "flowtype/space-before-type-colon": [
            2,
            "never"
        ],
        "flowtype/type-id-match": [
            2,
            "^([A-Z][a-z0-9]+)+Type$"
        ],
        "flowtype/union-intersection-spacing": [
            2,
            "always"
        ],
        "flowtype/use-flow-type": 1,
        "flowtype/valid-syntax": 1
    },

    "plugins": [
        "flowtype"
    ],
    "settings": {
        "flowtype": {
            "onlyFilesWithFlowAnnotation": false
        }
    }
}

```

Here's an example of an error I get even with no flow at top
![image](https://user-images.githubusercontent.com/14075632/27382329-5cfc602e-567e-11e7-89cd-bf5ab956bdc1.png)

Eslint + Flow + // @flow at the top of the file - 300 errors

I'm not sure why this is happening could anyone shed some light?

Thanks!

**Comment by luftywiranda13** [comment]
working exactly as expected. because you activate/use the recommended config.
see https://github.com/gajus/eslint-plugin-flowtype/issues/243

**Comment by TomYeoman** [comment]
Thanks for the prompt response @luftywiranda13 I had it in my head that these eslint rules would only be running if @flow was at the top, however if i'm now understanding correctly eslint doesn't care about that (Thats what my flow runner cares about).

All this does it make it so the flow additions do not make eslint fall over, as well as enforcing a few extra standards (which do not align with Airbnb) to make sure my code plays nicely with this package?

**Comment by luftywiranda13** [comment]
@TomYeoman hmm btw, as I can see in the screenshot you just added above, you haven't added type annotation to the return type. can i see your `flow check` CLI output?

and as a reminder:
* `eslint` will lint all `js` files by default except for special things like `node_modules/`, etc.
* `flow` will do type checking to all `js` files with `// @flow` on top of it

same as in #243, you have misconceptions about how both work

**Comment by TomYeoman** [comment]
@luftywiranda13 So in that file I just posted a screenshot of I don't really want any sort of "flow" linting going on is the issue. It's almost like I want a conditional config depending on whether (@flow) is present at the top of the JS file.

The error in the image is as expected (I am indeed missing the type annotation) but in this file I don't ever want to add flow notations. 

What i'm after is the ability to have single folder "/js" where I can have for example 5 normal JS files which will never have flow and only use airbnb linting. Then have another 5 files which and have a flow eslint config apply (which i'll have @ flow at the top)

Any idea if this is possible / makes sense? :D

**Comment by luftywiranda13** [comment]
> What i'm after is the ability to have single folder "/js" where I can have for example 5 normal JS files which will never have flow and only use airbnb linting....

it can be tricky. the easiest you can do is
```json
"flowtype": {
    "onlyFilesWithFlowAnnotation": true
}
```
https://github.com/gajus/eslint-plugin-flowtype#settings

or add `/* eslint-disable flowtype/* */` on top of each files you want to get the rules ignored

**Comment by TomYeoman** [comment]
@luftywiranda13 Oops very obvious now I should have checked all the configs I added! My onlyFilesWithFlowAnnotation was indeed set as false :man_facepalming: 

Thanks very much for all the help hopefully in the near future I can pass on the favor and contribute back to this project :)
