### ISSUE TITLE
flowtype/require-valid-file-annotation in specific folder only

### ISSUE THREAD

**Issue by Couto** [gajus/eslint-plugin-flowtype#246]
I would like to be able to specify that the rule `flowtype/require-valid-file-annotation` only applies to files inside a specific folder.

e.g.: with a project structure similiar to this:

```
.
├── config/
│   ├── qa.js
│   └── production.js
├── flow-typed/
├── node_modules/
├── src/
├── .eslintrc
├── .flowtype
└── package.json
```

ESLint will try to find for `// @flow` files inside the `config/` folder, where typical configuration files are present and while it's useful to lint them, is not so useful to have flow pragmas in there.

So the final rule would look something like (per example, i'm quite open to ideas): 

```
 "flowtype/require-valid-file-annotation": [
      2,
      "always", 
      "match": ["src/**/*.js"]
    ]
```

I don't mind to try to do a PR for this feature, but I would like to know first if it's a feature that actually makes sense and/or is a desired feature.

**Comment by gajus** [comment]
Thats outside of scope for this plugin.

Just create `.eslintrc` configuration within that folder applying the desired configuration.

**Comment by chris-feist** [comment]
You can enable/disable rules by adding eslint overrides
https://eslint.org/docs/user-guide/configuring#disabling-rules-only-for-a-group-of-files
