### ISSUE TITLE
Object Spread one type to another type is throwing internal eslint javascript errors

### ISSUE THREAD

**Issue by madole** [gajus/eslint-plugin-flowtype#247]
Valid flow causes eslint to throw javascript errors. 

The code for reproducing is [here in the flow REPL](https://flow.org/try/#0C4TwDgpgBAag9gGwK4FtoF4oG8BQV9QBuAhshAFxQB2qARhAE4A0eBSVAlsAM6XfAMOVAOYsAvjhyhIsRKggAlCNyQIeUTLgLUIwSgH54yNC20BjJHqiG5J1vgBmHBAgNH54ydOgAFBnDBuDWxWAEgAOkj3NCUVNW5TAg5uAFldQTNKWjhECGIqTxwHdjNgDjgqKGJaMwAKMH9A8j8A7gBKENCzCv5sKl0mKAtgQacXMWCG1vsoGe6qblzwhDhhWv7gNpwJHGq6rR0rLBIySgBGQfYuXigAchRbsUHWYcpj0iQKKAuoK55Ke6PZ6OZyubAnT7nS6cf53B5PWb4ZJpAQcTJQASfbZtIA) and is valid flow.

The first error is in this screenshot. 

![image](https://user-images.githubusercontent.com/3341965/27614877-b3d3a916-5be7-11e7-99bd-f3733c7362c5.png)

and when I disable `no-alert`, I run into this error.

![image](https://user-images.githubusercontent.com/3341965/27614887-c289d3cc-5be7-11e7-92ad-b8bb9387a245.png)

When I disable both of these rules, the lint works fine. 

Also if I do a union `A & B`, it works fine too. But object spread breaks.

**Comment by imaximix** [comment]
I can confirm, I've got the same problem, spread doesn't work.

**Comment by mrm007** [comment]
It has been reported [before](https://github.com/gajus/eslint-plugin-flowtype/issues/207), and labeled `help wanted`.
