### ISSUE TITLE
Fix no-duplicate-imports for import + import type

### ISSUE THREAD

**Issue by appsforartists** [gajus/eslint-plugin-flowtype#25]
eslint sees `import` and `import type` as equivalent, so it will throw a false `no-duplicate-imports` error if you import both types and code from a module:

```javascript
import type { ThingT } from './dep';
import { Thing } from './dep';
```

[They have declined to fix this](https://github.com/eslint/eslint/issues/6214), because it is Flow-specific.

Is this something that can be fixed in this plugin?

**Comment by gajus** [comment]
This is definitely fixable.

Can you try to do some debugging using babel-eslint parser and see if the types are the same? If they are, then this issue should be first raised with babel-eslint.

**Comment by benmosher** [comment]
FYI, [`import/no-duplicates`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) supports Flow imports. (not noted in the README, yet, but it does. since a while ago.)

**Comment by gajus** [comment]
I agree with @benmosher. This belongs better in [`import/no-duplicates`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md)
