### ISSUE TITLE
How to make simple example from flow docs work?

### ISSUE THREAD

**Issue by elvis-sik** [gajus/eslint-plugin-flowtype#265]
The example from here https://flow.org/en/docs/types/

```javascript
// @flow
function concat(a: string, b: string) {
  return a + b;
}

concat("A", "B"); // Works!
concat(1, 2); // Error!
```

I expected `eslint-plugin-flowtype` would say I'm using the function wrong. If I run `flow index.js`, I get the error. Is there a way to do that with eslint, so that I get the feedback inside my editor?

```json
  "devDependencies": {
    "babel-eslint": "^7.2.3",
    "eslint": "^4.5.0",
    "eslint-plugin-flowtype": "^2.35.0",
    "flow-bin": "^0.47.0"
  }
```

`.eslintrc`
```json
{
  "extends": [
    "plugin:flowtype/recommended"
  ],
  "parser": "babel-eslint",
  "plugins": [
    "flowtype"
  ]
}
```

**Comment by wxungang** [comment]
I have the same problem when using eslint in vueJs program.

**Comment by wxungang** [comment]
I want to break run webpack(or gulp) when someone's code has error use eslint-loader. (use 'flow status' just seems not very good!)

**Comment by lll000111** [comment]
**Flow** is the tool that checks your types!

**eslint** is the tool that checks your _syntax_. This plugin extends eslint to understand the Flow syntax.
