### ISSUE TITLE
Imported action types cause errors while local const action types do not.

### ISSUE THREAD

**Issue by yourfavorite** [gajus/eslint-plugin-flowtype#267]
I am using this plugin with Atom.

I have the following reducer that imports two action types from an actions file. When importing those action types from the actions file, I get flowtype-errors but if I instead define them inside of the reducer file, I don't get any errors.

This code causes `Property not found in 'object type'.` errors when referencing properties of action. ie - `action.prefs` and `action.id`.
```javascript
// @flow
import {
  UPDATE_PREF,
  LOAD_PREFS_SUCCESS
} from '../actions/prefs';

export type actionType = {
  +type: typeof LOAD_PREFS_SUCCESS,
  prefs: Array<{_id: string, value: any}>
} | {
  +type: typeof UPDATE_PREF,
  id: string,
  value: any
};

export default (state: {} = {}, action: actionType) => {
  console.log('type:', action.type);
  switch (action.type) {
    case LOAD_PREFS_SUCCESS: {
      const newState = {};
      action.prefs.forEach(p => {
        newState[p._id] = p.value;
      });
      return newState;
    }
    case UPDATE_PREF: {
      return { ...state, [action.id]: action.value };
    }
    default:
      return state;
  }
};
```

However if I replace the import statement at the top of the file with two const definitions, I get no errors.

```javascript
// @flow
const LOAD_PREFS_SUCCESS = 'LOAD_PREFS_SUCCESS';
const UPDATE_PREF = 'UPDATE_PREF';
```

**Comment by yourfavorite** [comment]
@gajus I feel like this is actually a bug and not a question. Unless I've done something wrong here. But I'm not sure how importing an exported const from another file should lint any differently than a const declared in the same file?

**Comment by gajus** [comment]
Can you share the full error?

It looks to me like you are describing Flow error, not eslint-plugin-flowtype error.

**Comment by yourfavorite** [comment]
I think you are correct this is a flow error. I'll move the issue over there :D
