### ISSUE TITLE
eslint approach has different results than flow check

### ISSUE THREAD

**Issue by aikar** [gajus/eslint-plugin-flowtype#270]
Hi, I want to preface that this is not a bug, as my code which I believe SHOULD be valid
>>> eslint src/
>>> flow check src/ | grep errors
Found 13 errors

I do not believe there should be errors, as the code is correct, and the errors reported make no sense to me.

How is this plugin invoking flow so that I can replicate the results?

**Comment by gajus** [comment]
This plugin does not invoke Flow. This plugin is for checking style errors in Flow type declarations. Flow is for checking type contracts.

**Comment by aikar** [comment]
@gajus oops sorry, appears this is from https://github.com/amilajack/eslint-plugin-flowtype-errors
