### ISSUE TITLE
Documentation generator doesn't handle settings property in assertion file

### ISSUE THREAD

**Issue by pnevyk** [gajus/eslint-plugin-flowtype#276]
Some rules use `settings` property in their assertions definition, e.g. to show that the rule is not applied when `onlyFilesWithFlowAnnotation` setting option is set to `true` and there is no such annotation in the code. However, documentation generator doesn't handle this property at all, so in docs there is wrong use case of the rule which is considered **not** a problem, without any note about `onlyFilesWithFlowAnnotation` setting.

**Comment by gajus** [comment]
Easy PR.

**Comment by gajus** [comment]
Thank you @pnevyk

**Comment by pnevyk** [comment]
@gajus I am glad I could help :)
