### ISSUE TITLE
[Request]: No contradicting checks

### ISSUE THREAD

**Issue by villesau** [gajus/eslint-plugin-flowtype#286]
Some times, especially when defining flow types afterwards the code gets dirty and unnecessary checks are left in place. For example:

```
function myFunc(num?: number): number {
  if (num === undefined) {
    return 1;
  }
  return num;
}
```

let's say we modify the code so that the function parameters are required and checked elsewehere:

```
function myFunc(num: number): number {
  if (num === undefined) {
    return 1;
  }
  return num;
}
```

Now we are left with unnecessary check. What we really want is to get rid of the check too:

```
function myFunc(num: number): number {
  return num;
}
```

However, the check is easily forgotten there as no linter nags about it.

Having unnecessary checks makes code more error prone, harder to understand and is against the purpose of static typing. Would be good to have a rule against this.

**Comment by gajus** [comment]
PR welcome.
