### ISSUE TITLE
`Disabled` shareable configuration

### ISSUE THREAD

**Issue by 102** [gajus/eslint-plugin-flowtype#288]
Maybe it worth to add `disabled` configuration? I can suggest at least one use-case: it's useful to disable this plugin in a folder with libdefs from `flow-typed`

**Comment by gajus** [comment]
> Maybe it worth to add disabled configuration

`disabled` what?

**Comment by 102** [comment]
I mean configuration with all the rules from this plugin disabled

**Comment by gajus** [comment]
How is this different from simply not including the plugin in the first place?

**Comment by 102** [comment]
As I described before, I have a nested folder `flow-typed` with additional `.eslintrc`, where I don't want this plugin to check anything. For the moment, I just write all the rules, which causing errors in the folder's config file, but it probably would be nice just to include something like `extends: plugin:flowtype/disabled'

**Comment by gajus** [comment]
Does ESLint not provide a way to disable all rules associated with one plugin? This sounds like a workaround.

**Comment by 102** [comment]
As far as I understand from https://github.com/eslint/eslint/issues/3419, there's no way to do it currently

**Comment by gajus** [comment]
@102 I'd rather help to advocate this change in the ESLint than to implement a local fix. I have pinged @nzakas on the original issue thread. If he doesn't follow up/ re-open the issue in a near future, I will follow up via other channels.

**Comment by mkay581** [comment]
any update on this issue?

**Comment by grit96** [comment]
Did anyone come up with a solution to this scenario?
