### ISSUE TITLE
Union types with a leading pipe fail parsing

### ISSUE THREAD

**Issue by pugnascotia** [gajus/eslint-plugin-flowtype#289]
Versions:
   * babel-eslint: ^7.1.1
   * eslint: 3.10.2
   * eslint-plugin-babel: 3.3.0
   * eslint-plugin-flowtype: ^2.39.1

According to the [Flow documentation](https://flow.org/en/docs/types/unions/#toc-union-type-syntax), union types can have a leading pipe character before the first member;

```
type Foo =
  | Type1
  | Type2
  | ...
  | TypeN
```

This currently causes a parse error, and I can't find a way of stopping ESLint parsing the file. I've modified the definition, but as this is a generated file that's a little icky.

**Comment by gajus** [comment]
PR welcome.

**Comment by pnevyk** [comment]
@pugnascotia I can't reproduce the parse error, even when I installed package versions you put here. However, parse errors are rather related to `babel-eslint`, try to upgrade this package if you can get this working.

**Comment by pugnascotia** [comment]
Finally confirmed that upgrading everything makes parsing work. Thanks!
