### ISSUE TITLE
flowtype/no-mutable-array fix action

### ISSUE THREAD

**Issue by jpolo** [gajus/eslint-plugin-flowtype#297]
The fix behavior changes Array to $ReadOnlyArray. This is not a good fixing behavior because : 
* It breaks flow validation when Array was actually wanted
* When using "fix on save" on Atom every Array is automatically transforms to $ReadOnlyArray : it is impossible to set as Array when wanted.

**Comment by gajus** [comment]
Whats the suggested action here?

**Comment by gajus** [comment]
You can just add `// eslint-disable-next-line flowtype/no-mutable-array` when a mutable array is desired.

**Comment by jpolo** [comment]
My suggestion is that the fix action must be removed. Fix action is supposed to automatically fix errors but should never breaks code. If there's a chance that the code is fixed in an unsafe way the eslint team seems  to just do nothing.
A good example is the "sort-keys" rule (https://github.com/eslint/eslint/issues/7714). The order of properties of an object is important at runtime in JS so they decided not to make a fix option.

**Comment by gajus** [comment]
> A good example is the "sort-keys" rule (eslint/eslint#7714). The order of properties of an object is important at runtime in JS so they decided not to make a fix option.

Funny enough, I am the advocate of the "sort-keys" rule. The rules are created to enforce a specific constraint; a fix enforces this constraint. If the intent is to ignore a specific case, then use the tools provided by ESLint to ignore specific code fragments.

**Comment by jpolo** [comment]
The problem is not on an opinion level but rather on a reliability level : nobody wants 'eslint --fix' to introduce bugs or incompatibilities.
The error is hardly fixable because there are too many unknown parameters. First, eslint does not know if replacing Array by $ReadOnlyArray will break flow typing. Secondly, eslint is not able to know if it was the initial intention of the dev or in opposition to the rule (only if the rule is disabled like you said).
