### ISSUE TITLE
no-flow-fix-me-comments not reporting issues

### ISSUE THREAD

**Issue by pathsny** [gajus/eslint-plugin-flowtype#307]
I have my .eslintrc rules set to include
{    'flowtype/no-flow-fix-me-comments': 'error'}

However, it never gives me errors or warnings about // $FlowFixMe annotations.

**Comment by gajus** [comment]
Well, it does pass the tests.

https://github.com/gajus/eslint-plugin-flowtype/blob/master/tests/rules/assertions/noFlowFixMeComments.js

Therefore, to assist further I'd need a test case where it does not.

**Comment by pathsny** [comment]
I have a project locally where it doe nothing. What works best here? A tarball of code?

**Comment by gajus** [comment]
A PR that replicates the error in the test case.

**Comment by gajus** [comment]
Until then I am going to close the issue.

**Comment by pathsny** [comment]
@gajus I'm afraid I do not know how to make it work with your test framework. But here is a minimal repro case
https://gist.github.com/pathsny/51ce729587febb85d7d49dcbe2e03a3f

As you can see when you run lint (you only get lint errors about the other lint rules I have chosen, but no-flow-fix-me-comments does not report any lint errors.

<img width="725" alt="screen shot 2018-01-30 at 18 21 40" src="https://user-images.githubusercontent.com/126134/35601961-80f16b66-05ea-11e8-847c-c231f3c8758b.png">

**Comment by mAAdhaTTah** [comment]
I'm also experiencing this on wp-gistpen. Added in [this commit](https://github.com/mAAdhaTTah/wp-gistpen/pull/175/commits/247008bfb46fc451e1e346798815a2fe674439b7). It's a WordPress plugin but the JS works w/o needing to get that set up. Also, [codeclimate](https://codeclimate.com/github/mAAdhaTTah/wp-gistpen/pull/175) is reporting the rule is missing.

Checking this locally, I don't see the `handleComment` function running at all. This is a version incompatibility. It looks like this plugin is running against v3.0.0 and I'm running v4.0.0. When I install v3.0.0, it works again, and produces a lot more errors.
