### ISSUE TITLE
Can't import flow types with sourceType script

### ISSUE THREAD

**Issue by alurim** [gajus/eslint-plugin-flowtype#310]
Reposting https://github.com/babel/babel-eslint/issues/474 since this project might be the more appropriate place to make the fix. 

TL;DR: I'm using Flow in a Node.js app with script sourceType files. I want to be able to import flow types into my files but I'm getting an eslint error because using import (and I only care about using import for types) is not allowed for script sourceType files.

**Comment by alurim** [comment]
Update! I'm wrapping import statements with comments and adding the words "flow-include" and things are working nicely. Would still be nice to have a more sane solution here. 

Not working:
```
import type { Foo } from './foo'
```

Working:
```
/* flow-include
import type { Foo } from './foo'
*/
```

**Comment by gajus** [comment]
Closing as stale.
