### ISSUE TITLE
Error 'This type is incompatible with' not showing on plugin

### ISSUE THREAD

**Issue by luciancaetano** [gajus/eslint-plugin-flowtype#311]
the code 
`` let x:number = 'abc'; ``

on flow show string. This type is incompatible with number.

but on eslint-plugin-flowtype this error is ignored.

**Comment by gajus** [comment]
`eslint-plugin-flowtype` is a code style linter. It is not designed to report Flow errors.

**Comment by luciancaetano** [comment]
could suggest a means of this specifically showing this error in linter, because for me it is very useful, I believe for many too.
