### ISSUE TITLE
Ignore type arguments and generics for no-weak-types 

### ISSUE THREAD

**Issue by k15a** [gajus/eslint-plugin-flowtype#315]
Hey,

I would like if there is an option for no-weak-types which excludes generics and type arguments.
This is useful if you want to have a generic which is more specific then a normal generic.

An example would be:
```js
// This function only works with objects.
function func<TData: Object>(obj: TData): TData {
	return obj
}
```

**Comment by gajus** [comment]
Closing as stale.
