### ISSUE TITLE
New timer globals

### ISSUE THREAD

**Issue by alexreardon** [gajus/eslint-plugin-flowtype#322]
Flow recently changed the return types for `setTimeout`, `setInterval` and `requestAnimationFrame`.

Rather than returning type `number` they now return different types:

https://github.com/facebook/flow/issues/5627

```js
const foo: TimeoutID = setTimeout(() => {}, 300);
const bar: IntervalID = setInterval(() => {}, 300);
const baz: AnimationFrameID = requestAnimationFrame(() => {});
```

Right now this throws an eslint warning because `TimeoutId`, `IntervalID` and `AnimationFrameID` are not defined

**Comment by gajus** [comment]
Configure globals.

https://eslint.org/docs/user-guide/configuring
