### ISSUE TITLE
Rule to prevent $FlowFixMe comments without explanation?

### ISSUE THREAD

**Issue by FezVrasta** [gajus/eslint-plugin-flowtype#323]
I'd like to be able to forbid `$FlowFixMe` comments if not followed by an explanation. The rule would look like:

Error:
```
// $FlowFixMe
```

Ok:
```
// $FlowFixMe this type is not behaving properly (See issue XXX)
```

Is there something like this available?

**Comment by pnevyk** [comment]
@FezVrasta I think this can be achieved using [no-flow-fix-me-comments](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-no-flow-fix-me-comments) and setting the first option to something like `.+` (one or more any characters) or any specific regex template you want.

**Comment by FezVrasta** [comment]
Thanks I did miss that option!

**Comment by zeorin** [comment]
The problem with that is that if you have dependencies that use flow, and they use a regular flow fix me comment without the extra match, their errors will no longer be supressed by flow.
