### ISSUE TITLE
Consider folder "flow-typed"?

### ISSUE THREAD

**Issue by simlu** [gajus/eslint-plugin-flowtype#324]
We are defining flow interfaces in the [flow-typed](https://github.com/flowtype/flow-typed/wiki/Importing-And-Using-Type-Definitions) folder, but they are not picked up and we get `no-use-before-define` when using them.

Any solution out there to this? What would be required to support this?

Thank you!

**Comment by gajus** [comment]
This would require some sort of logic for ESLint plugin to load the type definitions from `flow-typed` folder. It is currently not available.

**Comment by simlu** [comment]
@gajus Do you have a starting point in mind? Or an idea how to best approach this? How do other people define (config) objects that are passed through the code once and re-use the flow definition?

If you point me in the right direction I wouldn't mind taking a stab at a pr.

**Comment by gajus** [comment]
> How do other people define [..]

I've never used flow-typed folder. I always explicitly import types from a single file.

Off the top of my head, I cannot think what would a safe way to load type definitions from a file for a single execution. Please refer to the #213 issue – there is a reference to `eslint-babel` issue that seems to discuss similar scenario.

**Comment by gajus** [comment]
Closing as stale. If someone wants to address this, PR is welcome.
