### ISSUE TITLE
space-before-type-colon and space-after-type-colon doesn't work on variables

### ISSUE THREAD

**Issue by GarethSmall** [gajus/eslint-plugin-flowtype#329]
These properties are working every where else as expected except on variables:

For example the expected format of a typed variable:

`const someString : string = 'I am a string!';`

Examples of what eslint says is valid syntax:

`const someString: string = 'I am a string!';`
`const someString:string = 'I am a string!';`
`const someString :string = 'I am a string!';`

**Comment by gajus** [comment]
Sounds like a quick fix. PR welcome.

**Comment by GarethSmall** [comment]
I'll take a look at it tonight

**Comment by gajus** [comment]
You were missing an `always` option.

**Comment by GarethSmall** [comment]
How do you know what I was missing? o.o
