### ISSUE TITLE
Feature request: Add require-valid-file-annotation to recommended

### ISSUE THREAD

**Issue by KevinGrandon** [gajus/eslint-plugin-flowtype#331]
As flow coverage increases the quality of most web projects increases as well. This project is in a unique position to improve quality for everyone by adding `require-valid-file-annotation` to the default set of recommended rules.

Folks who are not ready can disable this rule by eslint config overrides, or per-file overrides. It would be great if we could add this to the default set, happy to submit a PR if so, but wanted to start discussion here first.

**Comment by gajus** [comment]
Closing as stale.
