### ISSUE TITLE
require-read-only-array should not cast $ReadOnlyArray when empty array intialization

### ISSUE THREAD

**Issue by gajus** [gajus/eslint-plugin-flowtype#335]
The current --fix behaviour changes empty array initialization to `$ReadOnlyArray`.

```diff
-const values: Array<$ReadOnlyArray<number | string | null>> = [];
+const values: $ReadOnlyArray<$ReadOnlyArray<number | string | null>> = [];

```

I think it is safe to assume that when variable is initialised with an empty array, then `$ReadOnlyArray` is undesired.

cc: @pnevyk

**Comment by pnevyk** [comment]
@gajus I will make the PR soon. Can you think of any other cases where `$ReadOnlyArray` fix is undesired?

**Comment by gajus** [comment]
Thank you.

I have run this rule against several fairly big large code bases and these were the only cases that I did not agree with the rule.

That said... I have fairly strict code style (https://github.com/gajus/eslint-config-canonical).
