### ISSUE TITLE
Proposal: Integrate eslint-plugin-flow-vars

### ISSUE THREAD

**Issue by zpao** [gajus/eslint-plugin-flowtype#35]
@zertosh wrote https://github.com/zertosh/eslint-plugin-flow-vars in order to make sure type imports and definitions are marked as used (helpful when used in conjunction with `no-unused-vars` & `no-undef`). It would be great to integrate the rules from that plugin here so we can consolidate the disparate Flow-related rules into a single plugin for Flow usage. Or maybe there's a different way to achieve the same thing (not sure if we can do it via a config now or something, I'm not familiar with how that works).

**Comment by zertosh** [comment]
I'd be more than happy to make a PR that moves the rules here. Then do one more release of `eslint-plugin-flow-vars` marking it as deprecated in favor of `eslint-plugin-flowtype`.

**Comment by gajus** [comment]
@zertosh Your PR is very welcome.

**Comment by gajus** [comment]
@zertosh, Just in case, if you need any help, please don't hesitate to contact me.

**Comment by zertosh** [comment]
PR is up

**Comment by zertosh** [comment]
@gajus also, how about if I move this one here too? https://github.com/facebook/nuclide/blob/8632e79/resources/eslint-plugin-nuclide-internal/type-alias-semi.js

**Comment by hzoo** [comment]
In https://github.com/babel/babel-eslint/issues/357, was planning on removing the logic to mark flow types as actually used (instead of marking everything as global) since it's difficult to maintain and can be wrong like mentioned and was going to recommend https://github.com/zertosh/eslint-plugin-flow-vars but now it seems this project instead?

**Comment by gajus** [comment]
> was going to recommend https://github.com/zertosh/eslint-plugin-flow-vars but now it seems this project instead?

Thats correct. Thanks to @zertosh

**Comment by zertosh** [comment]
@hzoo yup. I'm deprecating `eslint-plugin-flow-vars` in favor of `eslint-plugin-flowtype`.
