### ISSUE TITLE
Support for "@flow strict"?

### ISSUE THREAD

**Issue by callumlocke** [gajus/eslint-plugin-flowtype#364]
Flow supports [`@flow strict` and `@flow strict-local`](https://flow.org/en/docs/strict/) but I can't see any mention of these in the readme for this plugin.

It looks like I can use `require-valid-file-annotation` to enforce having an `@flow` in each file, but is there any way to enforce that it's always `@flow strict` or `@flow strict-local`?

**Comment by gajus** [comment]
If you are going to the effort of adding a requirement for `@flow strict` to ESLint, would it not make more sense to keep the plain `@flow` annotation and instead define the configuration for the project in `.flowconfig`?

**Comment by callumlocke** [comment]
It seems to be very tricky to configure this stuff in flowconfig. They have open issues about this and they don’t seem close to agreeing a way forward any time soon. Personally I want flow strict by default, and the ability to relax it to non-strict in certain files, but flowconfig doesn’t support this without major caveats.

So in the meantime, using the linter would be a nice alternative, as it would remind me to add flow strict whenever creating a new module (or maybe eslint —fix can even insert it for me), and it would give me the ability relax this to non-strict in select files using eslint’s various options for per-file error suppression, which are much more mature and flexible than Flow’s.

**Comment by gajus** [comment]
> It seems to be very tricky to configure this stuff in flowconfig. They have open issues about this and they don’t seem close to agreeing a way forward any time soon. 

Can you reference the relevant issues?

> So in the meantime, using the linter would be a nice alternative, as it would remind me to add flow strict whenever creating a new module (or maybe eslint —fix can even insert it for me)

This makes sense. A PR is welcome.

**Comment by xunuoi** [comment]
@gajus 

Hey, I also need the rule for flow strict as it mentioned here, so I created a PR for this. 

Could you help check and review the PR? https://github.com/gajus/eslint-plugin-flowtype/pull/414

Thanks🙏

**Comment by gajus** [comment]
Thank you
