### ISSUE TITLE
Add rule for warning on JSDoc @deprecated tag

### ISSUE THREAD

**Issue by harrytruong** [gajus/eslint-plugin-flowtype#367]
This is similar to the existing tslint rule `deprecation`:
- https://palantir.github.io/tslint/rules/deprecation/
- https://github.com/palantir/tslint/issues/825

I'm willing to do the work and submit a PR, if there's any interest in this?

------

### Implementation Goals

- [ ] implement lint warning on @deprecated functions/methods
```javascript
  // @deprecated 
  function foo(): void;
  // @deprecated use baz instead
  function bar(): void;
  /**
   * @deprecated see http://example.com/1234
   */
  function baz(): void;

  foo(); // Warning: 'foo' is deprecated.
  bar(); // Warning: 'bar' is deprecated. use baz instead
  baz(); // Warning: 'baz' is deprecated. see http://example.com/1234
```

- [ ] implement lint warning on @deprecated type declarations
```javascript
  // @deprecated use Foozy in new code.
  type Foo = string;
  type Foozy = 'foo' | 'bar' | 'baz';

  declare var foo: Foo; // Warning: type 'Foo' is deprecated. use Foozy in new code
```

- [ ] implement lint warning on @deprecated modules 
```javascript
  // from misc.js
  /**
   * Collection of misc utility functions
   * @deprecated use `foo` and `bar` modules instead.
   */
  const foo = () => ...;
  const bar = () => ...;
  export default { foo, bar };


  // from `otherFile.js`
  import utils from 'misc'; // Warning: 'misc' is deprecated. use `foo` and `bar` modules instead.
```

**Comment by gajus** [comment]
What makes this Flow specific?

Seems more appropriate for https://github.com/gajus/eslint-plugin-jsdoc.

**Comment by harrytruong** [comment]
ooo, yeah, implementing as part of `eslint-plugin-jsdoc` could also be more ideal.

I wanted to leverage it for deprecating flow type definitions though. Maybe I can start w/ `eslint-plugin-jsdoc`, and then if it's implemented, we can extend it here (similar to the way `flowtype/no-unused-expressions` works)?

**Comment by gajus** [comment]
If there is Flow specific behaviour, then sure. Otherwise, if it is just an alias, I don't see a use case.

**Comment by harrytruong** [comment]
Actually, going to close this issue. I found that `import/no-deprecated` from `eslint-plugin-import` works well enough for my needs!

It might be nice to add support for deprecating flowtypes, but maybe there's no real use for it.
