### ISSUE TITLE
Flow continue check files with onlyFilesWithFlowAnnotation=true

### ISSUE THREAD

**Issue by ravecat** [gajus/eslint-plugin-flowtype#372]
Flow check files without `@flow` instruction and spends considerable time on it

>husky > pre-commit (node v10.12.0)
yarn run v1.10.1
$ flow check
Found 0 errors
Done in 7.02s.
 ↓ Running tasks for src/**/*.{js,jsx} [skipped]
   → No staged files match src/**/*.{js,jsx}
 ↓ Running tasks for src/**/*.{js,jsx,json,css,md} [skipped]
   → No staged files match src/**/*.{js,jsx,json,css,md}

I set  `.eslintrc` with settings

```
  "settings": {
    "flowtype": {
      "onlyFilesWithFlowAnnotation": true
    }
  },
```

Current flow environment
```
"babel-preset-flow": "^6.23.0",
"eslint-plugin-flowtype": "^3.2.0",
"flow-bin": "^0.86.0",
"flow-watch": "^1.1.3",
"flow-webpack-plugin": "^1.2.0",
```

Use flow check in pre-commit hook, my scripts

```
"flow": "flow check",
"flow:watch": "flow-watch",
....
"precommit": "yarn flow && lint-staged",
```

Also can reproduce with repo (step by step paste to console)
1. `git clone https://github.com/ravecat/custom-create-react-app.git --single-branch --branch feature/update-flow-env`
2. `yarn`
3. `git commit --amend` and can see console output like above

Where am I wrong?

**Comment by gajus** [comment]
Wrong repository.

https://github.com/facebook/flow
