### ISSUE TITLE
warn about using "any" or "empty Object" or * as generic param

### ISSUE THREAD

**Issue by szagi3891** [gajus/eslint-plugin-flowtype#38]
const getValue = (): **any** => { ...}
or
render(): **any** {
or
    constructor(props: **Object**) {
        super(props);
or
Promise<*>

we need to prohibit these types of :) (any, blank Object, *)

**Comment by cloudkite** [comment]
see https://github.com/gajus/eslint-plugin-flowtype/pull/96

Does not include * but its a start

**Comment by danharper** [comment]
Closing thanks to @cloudkite in #96

**Comment by szagi3891** [comment]
Thank you :)
