### ISSUE TITLE
cannot suppress specific weak type

### ISSUE THREAD

**Issue by amis47** [gajus/eslint-plugin-flowtype#383]
eslint: 5.3.0
eslint-plugin-flowtype: 3.2.1

I was enabling `"flowtype/no-weak-types": 2` and wanna suppress existing weak type warnings but with no luck

```
// Options: [{"Object":false}]
type A = Object;
```

which still displays `Unexpected use of weak type "Object"`

looks like https://github.com/gajus/eslint-plugin-flowtype/blob/master/src/rules/noWeakTypes.js#L44 always return an empty array when do `lodash.get(context, 'options');`

**Comment by gajus** [comment]
There is a test case for this exact scenario.

https://github.com/gajus/eslint-plugin-flowtype/blob/aca85832758b9dc2c99c622867a287790b1db7dc/tests/rules/assertions/noWeakTypes.js#L294-L299
