### ISSUE TITLE
Suppress `no-undef` error for `_` type

### ISSUE THREAD

**Issue by glasserc** [gajus/eslint-plugin-flowtype#384]
[Flow 0.84](https://github.com/facebook/flow/releases/tag/v0.84.0) added support for wildcard types (`_`) in generics. These trigger `no-undef` errors in "stock" eslint, but because they do not represent actual type names, they never should. It's possible to disable them using `"flowtype/define-flow-type": "warn"`, but this also disables errors for actual types that aren't defined.

**Comment by gajus** [comment]
Just define globals.

https://eslint.org/docs/user-guide/configuring
