### ISSUE TITLE
Default rules and values?

### ISSUE THREAD

**Issue by kevinSuttle** [gajus/eslint-plugin-flowtype#39]
Maybe I'm missing it, but are the default rules and values documented somewhere? It's not clear reading the README or https://github.com/gajus/eslint-plugin-flowtype/tree/master/.README/rules

**Comment by gajus** [comment]
https://github.com/gajus/eslint-plugin-flowtype#configuration

**Comment by kevinSuttle** [comment]
Gotcha. Thanks.

**Comment by kevinSuttle** [comment]
Is there a preset for eslint-flowype?

**Comment by gajus** [comment]
> Is there a preset for eslint-flowype?

Not that I am aware of, no.
