### ISSUE TITLE
feat: add require-compound-type-alias option to create an exception for `x | null` types

### ISSUE THREAD

**Issue by gajus** [gajus/eslint-plugin-flowtype#390]
Most of the `require-compound-type-alias` errors that I get refer to explicit `or NULL` types, e.g.

```js
type PoolContextType = {|
  +log: LoggerType,
  +poolId: string,
  +query: TaggedTemplateLiteralInvocationType | null
|};

```

In this case creating a separate type would have little added value.

**Comment by gajus** [comment]
CC @pnevyk In case this is relevant to you too.

**Comment by pnevyk** [comment]
It looks like an easy fix to me, something that can be a good first PR. If anyone is interested, the task is to enhance both visitor rules in [this file](https://github.com/gajus/eslint-plugin-flowtype/blob/master/src/rules/requireCompoundTypeAlias.js) to check if `node.types.length == 2` and one of the nodes in `node.types` is of type `"NullLiteralTypeAnnotation"` if this option is enabled, and to update the rule schema.

@gajus If nobody takes this up, I will do it in (hopefully) near future in a free while.
