### ISSUE TITLE
Add a rule to require $ReadOnly Props and State for React components

### ISSUE THREAD

**Issue by kangax** [gajus/eslint-plugin-flowtype#397]
It's a good practice to annotate React' Props/State types as $ReadOnly, preventing mutation. 

Props can not be mutated in React and doing so could lead to unexpected behavior. State **can** be mutated but is recommended against, since it's not safe with multiple consecutive calls. There's a [lint rule to catch the latter](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-access-state-in-setstate.md) but it's very rudimental and doesn't handle all cases.

```js
type Props = $ReadOnly<{|…|}>
type State = $ReadOnly<{|…|}>

class Foo extends Component<Props, State> { ... }
```

I don't know if adding React-specific rules is OK in this plugin, but I wanted to throw this idea before making a custom lint rule in our codebase.

**Comment by gajus** [comment]
I think given that there is a big overlap between the React and Flow user-base, this is a reasonable request. Perhaps it is a better fit for https://github.com/yannickcr/eslint-plugin-react though?

**Comment by kangax** [comment]
@gajus I guess it could also be in eslint-plugin-react. It doesn't have any Flow-related rules at the moment and eslint-plugin-flowtype doesn't have any React-related rules at the moment :) 

I'll probably just make a PR here.
