### ISSUE TITLE
Rule request: enforce comma vs semicolon in Object properties

### ISSUE THREAD

**Issue by cjb** [gajus/eslint-plugin-flowtype#40]
Hi!  Would you accept a PR for a require-trailing-commas rule, enforcing this style?
```js
type Foo = {
  bar: string,
  baz: string,
}
```
Thanks!

**Comment by gajus** [comment]
Absolutely.

**Comment by cloudkite** [comment]
In addition to this would be nice to have a rule that enforces semi colon delimiters vs comma delimiters ie.

```
type Foo = {
  bar: string;
  baz: string;
}
```

vs

```
type Foo = {
  bar: string,
  baz: string,
}
```

@cjb Happy to pick this up if you are too busy? @gajus any suggestions for naming of these new rules?

**Comment by cjb** [comment]
@cloudkite That'd be great, don't wait for me!

**Comment by danharper** [comment]
I'd use eslint's comma-dangle rule as a starting point for the trailing commas.

**Comment by cloudkite** [comment]
I was thinking two new rules along the lines of:

1) `type-property-delimiter` 
with option of `'comma'` or `'semi'`

2) `type-property-delimiter-dangle`
this rule would not check if there is either a semi or comma on the last type property declaration. Could have the same options as http://eslint.org/docs/rules/comma-dangle

**Comment by cjb** [comment]
@cloudkite Those look good! But FWIW they don't add the feature in the issue description.

**Comment by cloudkite** [comment]
@cjb

using a combination of both would be the equivalent of `require-trailing-commas`

`type-property-delimiter: [2, 'comma']`
`type-property-delimiter-dangle:  [2, 'always']`

would have the following result
```
type Foo = {
  baa: number, // is fine
  bar: string; // error here as delimiter is semi instead of comma
  baz: string  // error here as no dangling/trailing comma
}
```

the reason for separating them would be to support people who prefer semi colons ie

`type-property-delimiter: ['semi']`
`type-property-delimiter-dangle:  ['always']`

```
type Foo = {
  baa: number; // is fine
  bar: string, // error here as delimiter is comma instead of semi
  baz: string  // error here as no dangling/trailing semi
}
```

**Comment by cjb** [comment]
@cloudkite Cool, thanks, I see now!

**Comment by danharper** [comment]
just found `eslint-plugin-babel` has a `babel/flow-object-type` rule for semicolon vs comma delimiters: https://github.com/babel/eslint-plugin-babel/blob/master/rules/flow-object-type.js

**Comment by cloudkite** [comment]
@danharper do think its worth copy over? Doesn't look like it handles dangling comma/semi

**Comment by gajus** [comment]
We can ask nicely, https://github.com/babel/eslint-plugin-babel/issues/93

**Comment by cloudkite** [comment]
cool if anyone wants to tackle this feel free. I dont know when I'll next have some free time

**Comment by danharper** [comment]
[`delimiter-dangle`](https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-delimiter-dangle) has been added in 2.16.0.

It doesn't support choosing the delimiter (it auto-fixes missing delimiters to a comma) as another rule can cover that (hopefully migrating the `babel/flow-object-type` plugin). I'll leave this issue open until then.

**Comment by danharper** [comment]
`object-type-delimiter` is deploying now as 2.23.0. I've ported the eslint-plugin-babel one.
