### ISSUE TITLE
React.forwardRef<Props, Instance> causes eslint parsing error.

### ISSUE THREAD

**Issue by tsnieman** [gajus/eslint-plugin-flowtype#401]
Given a flow annotation for React.forwardRef such as this:
```
const FancyInput = React.forwardRef<Props, HTMLDivElement>((props, ref) => (
  // ...
));
```

eslint currently doesn't know how to handle this and will produce an error such as:

```
error  Parse errors in imported module 'path/to/FancyInput': Line 69: Unexpected token
```

Can this package (`eslint-plugin-flow`) be updated to help `eslint` understand this syntax, or should I swim further upstream?

**Comment by gajus** [comment]
Further upstream. Most likely `babel-eslint`.
