### ISSUE TITLE
REQ: Option to ignore anonymous functions for require-return-type rule

### ISSUE THREAD

**Issue by turadg** [gajus/eslint-plugin-flowtype#41]
I want `flowtype/require-return-type` enabled in my codebase for `function` declarations and concise methods but it also complains on,
```
      .then(profile => Profile.fromJSON(profile));
```
and complying is a little ugly,
```
      .then((profile): Profile => Profile.fromJSON(profile));
```

I figure that Flow can generally infer the type in such small function bodies as are common with `=>` and when used anonymously there's no value in hinting to the IDE.

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/eslint-plugin-flowtype/pull/50

**Comment by gilbarbara** [comment]
Awesome!
But npm still shows 2.4.1 as the last version..

**Comment by gajus** [comment]
@gilbarbara Thank you for drawing my attention to it. Forgot `npm publish` in the workflow.

**Comment by gilbarbara** [comment]
👍 
I used to forget to publish to npm often.. Since you are using travis just add `on: tags:true` (and your the secure npm key) to the config.
