### ISSUE TITLE
Which version of eslint-plugin-flowtype is the last one to support eslint v5?

### ISSUE THREAD

**Issue by cjolowicz** [gajus/eslint-plugin-flowtype#419]
This plugin requires eslint `>=6.0.0`, while `eslint-config-airbnb` still requires eslint `^5.3.0`, pending airbnb/javascript#2036.

The requirement of eslint v6 was introduced in release [3.10.5](https://github.com/gajus/eslint-plugin-flowtype/releases/tag/v3.10.5). But seen that this specific change is marked as a bugfix, I'm wondering which version is actually recommended/safe to use with eslint v5? Would that be [3.9.1](https://github.com/gajus/eslint-plugin-flowtype/releases/tag/v3.9.1)?

Thanks.

**Comment by gajus** [comment]
v3.9.1

Sorry, in retrospect, it should have been a major version bump.
