### ISSUE TITLE
Feature Request: Do not require type annotations for variables where the type can be asserted

### ISSUE THREAD

**Issue by sigurdsvela** [gajus/eslint-plugin-flowtype#42]
In a lot of cases the type of a variable can be asserted from the context

```
const myArrayOfString: String[] = ['foo', 'bar', 'bad'];
myArrayOfString.map((s) => {});
```

In the above example for instance, it can be asserted that `s` is of type 'string'.
My request is a rule to require type annotations only where the type can not be asserted from the context.

This might not be possible/to much effort, but I thought I'd drop the idea. Hopefully, information about what variables type can be asserted is something Flow makes easily accessible.

**Comment by gajus** [comment]
Fixed in https://github.com/gajus/eslint-plugin-flowtype/pull/50
