### ISSUE TITLE
Is this project being maintained?

### ISSUE THREAD

**Issue by Brianzchen** [gajus/eslint-plugin-flowtype#462]
Hi @gajus. I want to check if this project is still being maintained. This project is a very solid base of eslint rules and it'd be a shame to not continue it especially if there's a need for it.

Reasons I felt like it may be abandoned:
- It's running travis  where none of the recent pull requests have been able to complete, this had a similar issue in flow-typed and we moved to github actions
- Looks like recent pull requests have been ignored by maintainers (since there's only 4 open right now, I'm talking about the 3 oldest ones)
- Looks like issues have mostly been ignored since June and they just sit there (though tags are still added when necessary which is nice but really doesn't help anyone except that we know it's been read and left alone)
- Issues that are important are just being closed instead of worked on. I don't think they should be closed just because they're stale. Open issues show a clear want from the community https://github.com/gajus/eslint-plugin-flowtype/issues/146

@gajus if you are not currently working on this project directly I thinking simply reviewing more pull requests would be helpful. Otherwise maybe we could consider new collaborators who can help breath more life into the project? Interested on your thoughts, thanks.

**Comment by gajus** [comment]
I am not actively using Flow, so that's why you are seeing less activity.

However, if anyone were to contribute to the project, I am happy to aid ensuring that releases are going out smoothly.

All the recent PRs have been merged.

**Comment by Brianzchen** [comment]
Thanks! Appreciate the quick response and we'll tag you when we come up with some changes

**Comment by Brianzchen** [comment]
Hi @gajus I want to reference this issue again and ask if you're still planning to maintain this project. Although I've seen some patches here and there that I appreciate.

Flow's community of eslint rules are still immature and there's lots of value to be added, a few people here and there are trying to contribute (including myself) and yet we're getting no response so it creates a loss of motivation and ultimately makes a community struggle to grow.
