### ISSUE TITLE
Possible to lint only files that have @flow at the top?

### ISSUE THREAD

**Issue by ericwooley** [gajus/eslint-plugin-flowtype#5]
I have a project where some parts have flow, and some do not. Is it possible to only lint the files with /* @flow */ at the top?

**Comment by gajus** [comment]
@ericwooley I am looking whether this can be solved using ESLint (https://github.com/eslint/eslint/issues/5481) configuration.

**Comment by nicks** [comment]
I'd like this too! I submitted a PR for it if that's OK. https://github.com/gajus/eslint-plugin-flowtype/pull/13

**Comment by gajus** [comment]
It could be a feature controlled using. http://eslint.org/docs/user-guide/configuring#adding-shared-settings

As it is, #13 PR accounts only for per-rule configuration and only for certain rules.

**Comment by nicks** [comment]
@gajus do you have opinions about what the setting API should look like?

re: "only for certain rules": well...those are the only rules a setting makes sense for? If my files don't have Flow types, then it doesn't matter if the typeIdMatch rule runs or not.

**Comment by gajus** [comment]
Regardless, a future proof solution is to have it as a shared config.

**Comment by nicks** [comment]
OK, i made it a setting flowtype:onlyFlowFiles

**Comment by gajus** [comment]
Thank you. Please squash the commits.

**Comment by nicks** [comment]
hmm? There's only one commit.

**Comment by gajus** [comment]
Sorry, habit - usually need to ask for this. Will review the PR when I am in front of a computer.
