### ISSUE TITLE
Change `@babel/plugin-transform-react-jsx` peer dependency to `@babel/plugin-syntax-jsx`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [gajus/eslint-plugin-flowtype#513]
Hi!

I noticed that the last release includes a peer dependency on `@babel/plugin-transform-react-jsx`. However, users might use other plugins to transform JSX (for example, https://github.com/infernojs/babel-plugin-inferno). Since you only care about _parsing_ JSX, you could change the peer dependency to `@babel/plugin-syntax-jsx`.

As an alternative, you could consider removing those two plugins and change
https://github.com/gajus/eslint-plugin-flowtype/blob/7989036225ebe23b19d6b92b16d33ef1c60a59bf/src/configs/recommended.json#L3-L10
to
```json
  "parserOptions": {
    "babelOptions": {
      "parserOpts": {
        "plugins": ["flow", "jsx"]
      }
    }
  },
```

It directly enables the plugins in the Babel parser (which are not "real" plugins that need to be installed), so `eslint-plugin-flowtype` users don't need to download the two Babel plugins which they might not need (for example, because they don't use JSX or because they don't use the recommended config).

**Comment by julienw** [comment]
Hey @gajus, what do you think about releasing a new version with this fix? Thanks :-)

**Comment by gajus** [comment]
Some tests are failing

**Comment by pascalduez** [comment]
Hi @gajus,

I'm wondering why in 449cb99f1b6d3bbbb66f5be55f497667f5b2cb31 you did not use `parserOpts` has mentioned earlier?

This dependency on babel plugins is quite problematic.  
For instance we have a monorepo where ESLint is run on a CI from the monorepo root.
But projects are still quite self enclosed, so we use the `--resolve-plugins-relative-to` for ESLint to find its plugins.
That obviously don't work with `eslint-plugin-flowtype` and the recent dependency on Babel plugins.
