### ISSUE TITLE
Recommended config uses "parser": "@babel/eslint", rather than   "parser": "@babel/eslint-parser",

### ISSUE THREAD

**Issue by athayes** [gajus/eslint-plugin-flowtype#522]
Reproduction steps:

In a new directory
1. `npm init`
2. `npm install eslint-plugin-flowtype`

Check the `node_modules/eslint-plugin-flowtype/dist/configs/recommended.json`

The parser is "@babel/eslint" but should be "@babel/eslint-parser"

**Comment by paveg** [comment]
@ATHayes 

This issue may be the same as https://github.com/gajus/eslint-plugin-flowtype/pull/514 .
Although the modified code has merged, it will take a long time to release to next version.

CI of master branch has failing test.

**Comment by mrtnzlml** [comment]
You might like to have a look at [flow-typed/eslint-plugin-ft-flow](https://github.com/flow-typed/eslint-plugin-ft-flow), which is supposed to be a more maintained version of this plugin and uses `@babel/eslint-parser`.
