### ISSUE TITLE
Add `require-parameter-type` option to ignore function expressions

### ISSUE THREAD

**Issue by migueloller** [gajus/eslint-plugin-flowtype#57]
Right now the option exists but only for arrow functions. It would be great to be able to ignore any function expression. The benefit would be for higher order functions that already have 100% Flow coverage that don't need their parameters annotated.

Example:

``` es6
type Fn = (param: string) => string;

function fn1(): Fn {
  return fn2(param) {
    return param;
  }
}
```

This will yield 100% Flow coverage without having to annotate `fn2`.

**Comment by gajus** [comment]
Closing as stale.
