### ISSUE TITLE
Error: Unsupported function signature.

### ISSUE THREAD

**Issue by vhf** [gajus/eslint-plugin-flowtype#6]
Hey,

I think I'm running into a bug with this plugin. It fails with `Unsupported function signature.` everytime I use destructuring with a default parameter.

Error is:

```
/mocha-babel-flow/node_modules/eslint-plugin-flowtype/dist/utilities/getParameterName.js:30
    throw new Error('Unsupported function signature.');
```

Repro repo: https://github.com/vhf/mocha-babel-flow (clone && `npm run lint`)

It seems `function x({ y = 1 } = {}) { }` is enough to make the crash happen.

Am I missing something?

**Comment by gajus** [comment]
v2.2.1 has been released.

**Comment by vhf** [comment]
Awesome @gajus, many thanks. :)
