### ISSUE TITLE
Using "declare interface" or "declare type" syntax incorrectly triggers "no-undef" rule while "declare class" does not have this issue.

### ISSUE THREAD

**Issue by AriaFallah** [gajus/eslint-plugin-flowtype#84]
Here is the error

```
1:19  error  'IFromPromise' is not defined  no-undef
```

and the code can be either

``` js
declare interface IFromPromise {
  value(): any,
  state(): 'pending' | 'resolved' | 'rejected'
}
```

or

``` js
declare type IFromPromise = {
  value(): any,
  state(): 'pending' | 'resolved' | 'rejected'
}
```

changing it to `declare class` fixes the issue, and an extremely weird edge case is just changing the name of the interface/type to `Response` fixes the issue as well.

**Comment by danharper** [comment]
just to check, have you enabled the [`define-flow-type`](https://github.com/gajus/eslint-plugin-flowtype#define-flow-type) rule?

**Comment by alexfedoseev** [comment]
Facing this as well, acts weird indeed. `define-flow-type` is enabled and suppresses errors where declarations are being used, but not where defined — not all, but some of them (see screen below).

<details>
<img width="808" alt="screen shot 2016-09-24 at 20 04 54" src="https://cloud.githubusercontent.com/assets/4244251/18808368/b38c3d76-8292-11e6-8e45-16876cf34e0b.png">
</details>

**Comment by dinomite** [comment]
I'm seeing this, too—enabling that rule suppresses usages of Flow types that I have declared, but I still get `no-undef` for (some) of those type declarations.

**Comment by AriaFallah** [comment]
@danharper don't know why I never replied...yes it is enabled.

**Comment by danharper** [comment]
Would someone mind sharing a repo with a minimal reproduction of this? I use Flow a lot, and never seen these issues myself.

**Comment by danharper** [comment]
Oh sorry, I just realised these are for `declare type`, which I don't use often so I may just have not run into this. A reproduction repo would help though :)

**Comment by AriaFallah** [comment]
@danharper making one right now.

**Comment by AriaFallah** [comment]
@danharper Here's a quick super contrived example: https://github.com/AriaFallah/eslint-plugin-flowtype-bug

Let me know if you run into the same issues.

**Comment by danharper** [comment]
Thanks 👍 

I haven't looked into the implementation yet, but I think this is because the types aren't used in the same file.

e.g. if I add `const x: Sum = {}` to the file, `Sum` no longer errors. It's probably not happening for `Response` because that's a global type defined by Flow (for `fetch()`).

I'll look into it when I get a chance.

Btw, you're probably best off using `export type` then `import type` where you need them instead of using `declare type`, which exposes them globally.

**Comment by AriaFallah** [comment]
I appreciate it. As for the `export type` and `import type` that's what I've been using, but for the project that spawned this issue, I think I just got lazy, and decided to pollute the global namespace 😅 .

**Comment by dendril** [comment]
Any news about this issue?

**Comment by thurt** [comment]
im interesting in understanding if there is a solution for this as well.

**Comment by thurt** [comment]
as stop-gap solution, you can add all of your declared types/interfaces as globals in a comment

http://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by MikeYermolayev** [comment]
Any news on this issue? Faced this on the new project. Tried to enable define-flow-type but no result. There are a lot declarations of global types so I don't really want to refactor everything to use `export` `import`

**Comment by gajus** [comment]
No plans to support global types. Closing as stale.
