### ISSUE TITLE
Support /* Flow Comments */

### ISSUE THREAD

**Issue by chrisblossom** [gajus/eslint-plugin-flowtype#87]
Are there any plans to support defining flow types as comments as shown here: [https://flowtype.org/blog/2015/02/20/Flow-Comments.html](https://flowtype.org/blog/2015/02/20/Flow-Comments.html)?

**Comment by arvitaly** [comment]
+1 I don't want compile my JS-code)

**Comment by ami44** [comment]
+1

**Comment by busybeaver** [comment]
This one would be great. I only use Flow via comments...

**Comment by HyperBrain** [comment]
I'm stuck on this too. We use comment annotation style for some external modules that are not compiled/processed via babel, but have flow enabled using the comment annotation style.

**Comment by simlu** [comment]
We would love to see this one as well since we don't have a compile step.

**Comment by hczhcz** [comment]
Here is a simple solution: https://github.com/hczhcz/eslint-plugin-flowtype-comment
Before someone develops a correct one)

**Comment by gajus** [comment]
`eslint-plugin-flowtype-comment` is a valid solution for anyone who wants to use comments syntax.

**Comment by isiahmeadows** [comment]
@gajus Their README is a bit unsettling...not sure I'd feel comfortable using it.

**Comment by hczhcz** [comment]
@isiahmeadows 
The solution involves some string tricks instead of actually parsing the source code. It would not have problem in most cases. But, if you are writing code related to safety or a lot of money, it is better to remove flow comments.

**Comment by gajus** [comment]
If there was a good reason to use Flow comment syntax over just Flow annotations, I would prioritise this more. At the glance, I don't see any issues with @hczhcz implementation. If anything, effort should go improving it. I don't see a straightforward way of supporting it in this plugin.
