### ISSUE TITLE
Add rule to enforce one array notation style

### ISSUE THREAD

**Issue by opatut** [gajus/eslint-plugin-flowtype#94]
Instead of `Array<string>` one can write `string[]`.

I would like to see a rule that enforces either style. 

Bonus points for an option that only enables the rule on "simple" types, such as `TFoo` or `string` (i.e. enforce `string[]` instead of `Array<string>`) but not on more complex types, e.g. `?TFoo` (compare `Array<?TFoo>` and `(?TFoo)[]`) or `{id: number}` (compare `({id: number})[]` and `Array<{id: number}>`). PS: I would count `Promise<Foo>` and other polymorphic types as simple types, so `Promise<Foo>[]` is legal.

**Comment by danharper** [comment]
I guess this too `?(string[])`

**Comment by opatut** [comment]
So basically we have four rules:

* require-simple-array-shorthand
* no-simple-array-shorthand
* require-complex-array-shorthand
* no-complex-array-shorthand

That way, one can decide to enforce either style for simple types, but not enforce them for complex styles. Or vice versa. Or enforce different styles for different complexities. Or the same for both. Or none at all. Wow. This is complicated.

**Comment by pnevyk** [comment]
@opatut I created a PR (#278) but I need opinions on some points. It would be great if you (or anyone else interested in this feature) leave a comment there.

**Comment by gajus** [comment]
Fixed.
