### ISSUE TITLE
Rule Request: Enforce bool or boolean

### ISSUE THREAD

**Issue by zpao** [gajus/eslint-plugin-flowtype#97]
Unfortunately both are valid types (the same type luckily). It would be great to enforce one or the other.

**Comment by vjeux** [comment]
A quick grep on Facebook codebase shows that `boolean` is used 20x more then `bool` if you need a data point

**Comment by vjeux** [comment]
Docs also don't even mention `bool` https://flowtype.org/docs/builtins.html#boolean

**Comment by danharper** [comment]
Added in v2.13.0 :)

**Comment by zpao** [comment]
❤️ thanks @danharper!
